"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),fixture=require("./fixtures/adapters/zhengfang-v9-conformance.json");
const root=path.resolve(__dirname,"../app/assets/adapters"),contract=require(path.join(root,"timetable-adapter-contract.js")),diagnostics=require(path.join(root,"adapter-diagnostics.js")),primitives=require(path.join(root,"parsing-primitives.js")),adapter=require(path.join(root,"zhengfang-v9.js"));
assert.equal(contract.validate(adapter).ok,true);assert.equal(adapter.interfaceVersion,1);assert.deepEqual(adapter.supportedCaptureVersions,[1]);assert(adapter.limits.maxInputBytes>0&&adapter.limits.maxMeetings>0);
for(const [expression,weeks] of Object.entries(fixture.validWeekExpressions))assert.deepEqual(primitives.parseWeeks(expression),weeks);for(const expression of fixture.invalidWeekExpressions)assert.equal(primitives.parseWeeks(expression),null);
assert.deepEqual(primitives.parsePeriodRange("第1-2周（3-4节）"),{startPeriod:3,endPeriod:4});assert.equal(primitives.weekdayFromCellId("5-2"),5);assert.equal(primitives.weekdayFromCellId("8-1"),null);
const diagnostic=diagnostics.create({adapterId:"zhengfang-v9",stage:"PARSE",code:"UNSUPPORTED_SYSTEM",message:"Unknown https://private.example/path",detail:"token\u0000value"});assert(!diagnostic.message.includes("private.example"));assert(!diagnostic.developerDetail.includes("\u0000"));
for(const field of contract.REQUIRED_METHODS){const broken={...adapter,[field]:null};assert.equal(contract.validate(broken).code,"MISSING_ADAPTER_METHOD")}
assert.equal(contract.validate({...adapter,interfaceVersion:999}).code,"UNSUPPORTED_INTERFACE_VERSION");assert.equal(fixture.validCases.length,8);assert.equal(fixture.invalidCases.length,10);
const source=fs.readFileSync(path.join(root,"zhengfang-v9.js"),"utf8");assert(!/indexedDB|localStorage|TimetableRepository|\.put\s*\(/.test(source),"adapter must not persist");
const profileApi=require("../app/assets/timetable/school-profile.js"),factory=require("../app/assets/adapters/public-profile-factory.js"),normalized=require("../app/assets/timetable/normalized-import.js"),profile=factory.create({origin:"https://portal.example.invalid",adapterId:adapter.id,adapterVersion:adapter.version,timezone:"UTC",periodDefinitions:{1:{start:"08:00",end:"08:45"}}}),draft=normalized.create({profile,adapter,semester:{academicYear:"2026-2027",term:"1"},meetings:[{courseName:"Course Alpha",weekday:1,startPeriod:1,endPeriod:1,weeks:[1]}],source:adapter.id});assert.equal(profile.id,"public-zhengfang-v9");assert.equal(draft.school.id,null);assert.equal(draft.school.name,null);assert.equal(profileApi.registry.list().length,0);
console.log(JSON.stringify({result:"ADAPTER_CONFORMANCE_PASS",interfaceVersion:1,fixtureCases:18}));
