"use strict";
const assert=require("node:assert/strict"),http=require("node:http"),fs=require("node:fs"),path=require("node:path");
const {chromium}=require("playwright"),site=path.resolve(__dirname,"../app"),out=require("./local-artifacts").evidenceDirectory("ai-import-hardening");
const executablePath=[path.join(process.env.LOCALAPPDATA||"","Google","Chrome","Application","chrome.exe"),path.join(process.env["PROGRAMFILES(X86)"]||"","Microsoft","Edge","Application","msedge.exe")].find(fs.existsSync);
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,"fixtures/ai-visual-timetable-synthetic.json"),"utf8")).importPayload;
const columnShift=JSON.parse(fs.readFileSync(path.join(__dirname,"fixtures/ai-weekday-column-shift-synthetic.json"),"utf8"));
const retainAll=async page=>{for(const group of await page.locator("#fileConflictItems .file-conflict-group").all())await group.locator("summary").click();for(const button of await page.locator("#fileConflictItems .file-conflict-item button").filter({hasText:"确认这是真实冲突，保留两者"}).all())await button.click()};
const server=http.createServer((req,res)=>{let name=decodeURIComponent(new URL(req.url,"http://local").pathname);if(name.endsWith("/"))name+="index.html";const file=path.resolve(site,"."+name);if(!file.startsWith(site+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return}res.writeHead(200,{"content-type":file.endsWith(".js")?"application/javascript":file.endsWith(".css")?"text/css":"text/html"});res.end(fs.readFileSync(file))});
const variants=[[390,"light"],[390,"dark"],[430,"light"],[430,"dark"],[1024,"light"],[1024,"dark"],[1440,"light"],[1440,"dark"]];
(async()=>{
  fs.mkdirSync(out,{recursive:true});await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
  const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,executablePath});
  const results=[];
  try{
    for(const [width,theme] of variants){
      const context=await browser.newContext({viewport:{width,height:width<700?844:900},colorScheme:theme,isMobile:width<700,hasTouch:width<700});
      const page=await context.newPage(),errors=[];page.on("pageerror",error=>errors.push(error.message));
      await page.goto(base+"/import/?method=clipboard");
      await page.locator("#clipboardText").fill(JSON.stringify(fixture));
      await page.locator("#clipboardPreview").click();
      await page.locator("#filePreview:not([hidden])").waitFor();
      assert(await page.locator("#fileCalendarContext").isVisible());
      assert.match(await page.locator("#fileConflictWarning").innerText(),/2 组课程时间冲突/);
      assert(await page.locator("#fileConflictReview").isVisible());
      await page.locator("#fileConflictDetails summary").click();
      assert.match(await page.locator("#fileConflictItems").innerText(),/重叠/);
      assert(await page.locator("#fileDateDisplay").isHidden());
      assert(await page.locator("#fileSave").isDisabled());
      await page.locator("#fileSemesterStart").fill("2026-08-31");
      assert(await page.locator("#fileDateDisplay").isHidden());
      assert(await page.locator("#fileSave").isDisabled(),"conflict requires explicit acknowledgement");
      await retainAll(page);
      await page.locator("#fileConflictConfirm").check();
      const importShot=`import-conflict-${width}-${theme}.png`;
      await page.locator("#filePreview").screenshot({path:path.join(out,importShot)});
      await page.locator("#fileSave").click();
      await page.waitForFunction(()=>/已保存/.test(document.querySelector("#fileSubmitMessage")?.textContent||""));
      const savedDate=await page.evaluate(async()=>{const row=await AnyClassTimetableRepository.getActiveTimetable(),bundle=await AnyClassTimetableRepository.readTimetableBundle(row.timetableId);return bundle.term.semesterStartDate});
      assert.equal(savedDate,"2026-08-31");
      await page.goto(base+"/timetable/");await page.locator("#app:not([hidden])").waitFor();
      while(await page.locator("#previous").isEnabled())await page.locator("#previous").click();
      await page.locator("#next").click();
      assert.match(await page.locator("#conflictCount").innerText(),/1 组冲突/);
      const timetableShot=`timetable-conflict-${width}-${theme}.png`;
      await page.screenshot({path:path.join(out,timetableShot)});
      if(width>=700){
        assert.equal(await page.locator(".conflict-group-card").count(),1);
        const cardWidth=await page.locator(".conflict-group-card").evaluate(node=>node.getBoundingClientRect().width);
        assert(cardWidth>=120,`group card too narrow: ${cardWidth}`);
        await page.locator(".conflict-group-card").click();
        assert.equal(await page.locator("#conflictGroupItems button").count(),3);
        await page.locator("#conflictGroupDialog").screenshot({path:path.join(out,`conflict-group-detail-${width}-${theme}.png`)});
        await page.locator("#conflictGroupItems button").first().click();
        assert(await page.locator("#courseDialog").isVisible());
        if(width===1024&&theme==="light"){
          await page.locator("#closeDialog").click();
          await page.locator("#courseDialog").waitFor({state:"hidden"});
          await page.locator("#previous").click();
          assert.match(await page.locator("#conflictCount").innerText(),/1 组冲突/);
          await page.screenshot({path:path.join(out,"timetable-two-way-1024-light.png")});
          await page.locator(".conflict-group-card").click();
          assert.equal(await page.locator("#conflictGroupItems button").count(),2);
        }
      }else assert.equal(await page.locator(".mobile-course.conflicting").count(),3);
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
      assert.deepEqual(errors,[]);
      results.push({width,theme,importShot,timetableShot,savedDate,grouped:width>=700});
      await context.close();
    }
    for(const width of [390,430]){
      const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true});
      const page=await context.newPage(),meetings=[];
      for(let index=0;index<15;index++)for(const suffix of ["A","B"])meetings.push({courseName:`Conflict ${index} ${suffix}`,weekday:Math.floor(index/3)+1,startPeriod:index%3+1,endPeriod:index%3+1,weeks:[1],teacher:null,locationRaw:"Example Room"});
      await page.goto(base+"/import/?method=clipboard");
      await page.locator("#clipboardText").fill(JSON.stringify({...fixture,school:{id:null,name:null},meetings}));
      await page.locator("#clipboardPreview").click();
      await page.locator("#filePreview:not([hidden])").waitFor();
      assert.equal(await page.locator("#fileSchoolName").inputValue(),"");
      await page.locator("#fileSchoolName").fill("示例大学");
      await page.locator("#fileSemesterStart").fill("2026-08-31");
      await page.locator("#fileConflictDetails summary").tap();
      assert.equal(await page.locator("#fileConflictItems .file-conflict-item").count(),15);
      await page.locator("#fileConflictItems .file-conflict-item").last().scrollIntoViewIfNeeded();
      await retainAll(page);
      await page.locator(".file-conflict-confirm").tap();
      assert(await page.locator("#fileConflictConfirm").isChecked(),`${width}px label tap checks acknowledgement`);
      assert(await page.locator("#fileSave").isEnabled(),`${width}px review enables save only after acknowledgement`);
      await page.locator("#fileSave").scrollIntoViewIfNeeded();
      const hit=await page.locator("#fileSave").evaluate(button=>{const rect=button.getBoundingClientRect(),dock=document.querySelector(".shell-bottom-nav")?.getBoundingClientRect(),node=document.elementFromPoint(rect.left+rect.width/2,rect.top+rect.height/2);return {hit:node===button||button.contains(node),dockOverlap:!!dock&&rect.bottom>dock.top&&rect.top<dock.bottom,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,pointerEvents:getComputedStyle(button).pointerEvents}});
      assert(hit.hit&&!hit.dockOverlap&&!hit.overflow&&hit.pointerEvents!=="none",`${width}px final action reachable above Dock: ${JSON.stringify(hit)}`);
      await page.locator("#fileCancel").tap();
      assert(await page.locator("#filePreview").isHidden(),`${width}px cancel closes preview`);
      assert.notEqual(await page.locator(".shell-bottom-nav").evaluate(node=>getComputedStyle(node).display),"none",`${width}px Dock restored`);
      await context.close();
    }
    const context=await browser.newContext(),page=await context.newPage();
    await page.goto(base+"/import/?method=file");
    await page.locator("#fileInput").setInputFiles({name:"synthetic.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify({...fixture,school:{id:"school-demo",name:"Example University"}}))});
    await page.locator("#filePreview:not([hidden])").waitFor();
    assert(await page.locator("#fileCalendarContext").isVisible());
    assert(await page.locator("#fileSave").isDisabled());
    await page.locator("#fileSemesterStart").fill("2026-09-07");await page.locator("#fileConflictDetails summary").click();await retainAll(page);await page.locator("#fileConflictConfirm").check();await page.locator("#fileSave").click();
    await page.waitForFunction(()=>/已保存/.test(document.querySelector("#fileSubmitMessage")?.textContent||""));
    const date=await page.evaluate(async()=>{const row=await AnyClassTimetableRepository.getActiveTimetable(),bundle=await AnyClassTimetableRepository.readTimetableBundle(row.timetableId);return bundle.term.semesterStartDate});
    assert.equal(date,"2026-09-07");await context.close();
    const unknownFileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),unknownFilePage=await unknownFileContext.newPage();
    await unknownFilePage.goto(base+"/import/?method=file");
    await unknownFilePage.locator("#fileInput").setInputFiles({name:"unknown-school.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify({...fixture,school:{id:null,name:null},meetings:[fixture.meetings[0]]}))});
    await unknownFilePage.locator("#filePreview:not([hidden])").waitFor();
    assert.equal(await unknownFilePage.locator("#fileSchoolName").inputValue(),"");
    assert(await unknownFilePage.locator("#fileSave").isDisabled());
    await unknownFilePage.locator("#fileSchoolName").fill("示例大学");
    await unknownFilePage.locator("#fileSemesterStart").fill("2026-09-07");
    await unknownFilePage.locator("#fileSave").click();
    await unknownFilePage.waitForFunction(()=>document.querySelector("#filePreview")?.dataset.importState==="SUCCESS");
    assert.equal(await unknownFilePage.evaluate(async()=>{const table=await AnyClassTimetableRepository.getActiveTimetable();return table.schoolId}),null);
    await unknownFileContext.close();
    const duplicateContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
    const duplicatePage=await duplicateContext.newPage(),now=new Date(),weekday=now.getDay()||7,monday=new Date(now.getFullYear(),now.getMonth(),now.getDate()-(weekday-1));
    const dateText=[monday.getFullYear(),String(monday.getMonth()+1).padStart(2,"0"),String(monday.getDate()).padStart(2,"0")].join("-");
    const row={courseName:"AI Course",weekday,startPeriod:1,endPeriod:2,weeks:[1],teacher:"Teacher A",locationRaw:"Room A",isAdjusted:false};
    const duplicateFixture={...fixture,meetings:[row,{...row,courseName:" AI  Course ",teacher:" teacher a "},{...row,weeks:[2]}]};
    await duplicatePage.goto(base+"/import/?method=clipboard");
    await duplicatePage.locator("#clipboardText").fill(JSON.stringify(duplicateFixture));await duplicatePage.locator("#clipboardPreview").click();
    await duplicatePage.locator("#filePreview:not([hidden])").waitFor();
    assert.match(await duplicatePage.locator("#fileConflictWarning").innerText(),/完全重复/);
    assert.equal(await duplicatePage.locator("#fileMeetingCount").innerText(),"2");
    await duplicatePage.locator("#fileSemesterStart").fill(dateText);
    await duplicatePage.waitForFunction(()=>!document.querySelector("#fileSave").disabled);
    await duplicatePage.locator("#fileSave").click();await duplicatePage.waitForFunction(()=>document.querySelector("#filePreview")?.dataset.importState==="SUCCESS");
    await duplicatePage.goto(base+"/today/");await duplicatePage.locator("#app:not([hidden])").waitFor();
    await duplicatePage.locator("#todayList .course-row").first().waitFor();
    assert.equal(await duplicatePage.locator("#todayList .course-row").count(),1,"duplicate AI row must not produce a second Today card");
    await duplicateContext.close();
    for(const width of [390,430]){
      const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true});
      const page=await context.newPage(),errors=[];page.on("pageerror",error=>errors.push(error.message));
      await page.goto(base+"/import/?method=clipboard");
      await page.locator("#clipboardText").fill(JSON.stringify(columnShift.aiOutputWithWeekdayError));
      await page.locator("#clipboardPreview").tap();
      await page.locator("#filePreview:not([hidden])").waitFor();
      assert.match(await page.locator("#fileConflictWarning").innerText(),/1 组课程时间冲突/);
      await page.locator("#fileConflictDetails summary").tap();
      assert.match(await page.locator("#fileConflictItems").innerText(),/Synthetic Physics.*Synthetic Writing/s);
      await page.locator("#fileConflictEdit").scrollIntoViewIfNeeded();
      const editHit=await page.locator("#fileConflictEdit").evaluate(button=>{const rect=button.getBoundingClientRect(),node=document.elementFromPoint(rect.left+rect.width/2,rect.top+rect.height/2),dock=document.querySelector(".shell-bottom-nav")?.getBoundingClientRect();return {hit:node===button||button.contains(node),dockOverlap:!!dock&&rect.bottom>dock.top&&rect.top<dock.bottom,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth}});
      assert(editHit.hit&&!editHit.dockOverlap&&!editHit.overflow,`${width}px conflict edit action must be tappable: ${JSON.stringify(editHit)}`);
      await page.locator("#fileConflictEdit").tap();
      assert(await page.locator("#filePendingEditor").isVisible());
      const writingValue=await page.locator("#filePendingGroup option").evaluateAll(options=>options.find(option=>option.textContent.includes("Synthetic Writing"))?.value);
      assert(writingValue,"synthetic conflict course must be available in pending editor");
      await page.locator("#filePendingGroup").selectOption(writingValue);
      assert.equal(await page.locator("#filePendingWeekday").inputValue(),"1");
      await page.locator("#filePendingWeekday").fill("8");
      await page.locator("#filePendingApply").tap();
      assert.match(await page.locator("#filePendingError").innerText(),/星期/);
      assert(await page.locator("#fileConflictReview").isVisible(),"invalid edit must leave conflict unresolved");
      await page.locator("#filePendingWeekday").fill("2");
      await page.locator("#filePendingApply").tap();
      await page.locator("#filePendingEditor").waitFor({state:"hidden"});
      await page.locator("#fileConflictReview").waitFor({state:"hidden"});
      const correctedPreview=await page.locator("#fileRows").innerText();
      assert.match(correctedPreview,/Synthetic Writing.*周2/s,"corrected weekday must appear in preview");
      await page.locator("#fileSchoolName").fill("Example University");
      await page.locator("#fileSemesterStart").fill("2026-08-31");
      await page.waitForFunction(()=>!document.querySelector("#fileSave").disabled);
      await page.locator("#fileSave").tap();
      await page.waitForFunction(()=>document.querySelector("#filePreview")?.dataset.importState==="SUCCESS");
      const first=await page.evaluate(async()=>{const bundle=await AnyClassTimetableRepository.readActiveBundle();return {id:bundle.table.timetableId,courses:bundle.model.courses.map(course=>({name:course.title,weekday:course.weekday}))}});
      assert.deepEqual(first.courses.map(course=>course.weekday).sort(),[1,2],"corrected weekdays must persist");
      await page.goto(base+"/today/");await page.locator("#app:not([hidden])").waitFor();
      const reloaded=await page.evaluate(async()=>{const bundle=await AnyClassTimetableRepository.readActiveBundle();return {id:bundle.table.timetableId,courses:bundle.model.courses.map(course=>({name:course.title,weekday:course.weekday}))}});
      assert.deepEqual(reloaded,first,"reload must preserve the corrected timetable");
      if(width===390){
        const second=await page.evaluate(async()=>{const table=await AnyClassTimetableRepository.createTimetable({label:"Synthetic B"});await AnyClassTimetableRepository.setActiveTimetable(table.timetableId);return table.timetableId});
        await page.goto(base+"/import/?method=clipboard");
        const corrected={...columnShift.aiOutputWithWeekdayError,meetings:columnShift.aiOutputWithWeekdayError.meetings.map((meeting,index)=>({...meeting,weekday:index+1}))};
        await page.locator("#clipboardText").fill(JSON.stringify(corrected));await page.locator("#clipboardPreview").tap();await page.locator("#filePreview:not([hidden])").waitFor();
        assert.match(await page.locator("#fileImportTarget").innerText(),/Synthetic B/,"selected B is the import target");
        await page.locator("#fileSchoolName").fill("Example University");await page.locator("#fileSemesterStart").fill("2026-08-31");
        await page.waitForFunction(()=>!document.querySelector("#fileSave").disabled);
        await page.locator("#fileSave").tap();await page.waitForFunction(()=>document.querySelector("#filePreview")?.dataset.importState==="SUCCESS");
        const isolated=await page.evaluate(async ids=>{const repo=AnyClassTimetableRepository,a=await repo.readTimetableBundle(ids.a),b=await repo.readTimetableBundle(ids.b),active=await repo.getActiveTimetable();return {a:a.model.courses.map(course=>[course.title,course.weekday]),b:b.model.courses.map(course=>[course.title,course.weekday]),active:active.timetableId}}, {a:first.id,b:second});
        assert.deepEqual(isolated.a,isolated.b,"same synthetic source imported into B must not alter A");
        assert.equal(isolated.active,second,"B remains selected after import");
      }
      assert.deepEqual(errors,[],`${width}px browser errors`);
      await context.close();
    }
    console.log(JSON.stringify({result:"PASS",screenshots:results.length*2+5,directory:out,fileClipboardParity:"PASS",registeredDemoDoesNotBypassDate:"PASS",genuineConflictsImportable:"PASS",results},null,2));
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
})().catch(error=>{console.error(error);process.exitCode=1});
