"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
require("../app/assets/timetable/normalized-import.js");
const file=require("../app/assets/timetable/import-file-core.js");
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,"fixtures/ai-visual-timetable-synthetic.json"),"utf8"));
const columnShift=JSON.parse(fs.readFileSync(path.join(__dirname,"fixtures/ai-weekday-column-shift-synthetic.json"),"utf8"));
const multiColumn=JSON.parse(fs.readFileSync(path.join(__dirname,"fixtures/ai-weekday-multi-column-synthetic.json"),"utf8"));
assert.deepEqual(fixture.sourceGrid.headers,["星期一","星期二","星期三","星期四","星期五","星期六","星期日"]);
assert.equal(fixture.importPayload.semester.semesterStartDate,undefined);
assert.equal(fixture.importPayload.meetings.filter(row=>row.courseName==="Course A").length,2);
const parsed=file.parseText(JSON.stringify(fixture.importPayload));
assert.equal(parsed.meetings.length,6);
for (const school of [{id:null,name:null},{name:null}]) {
  const unknownSchool=file.parseText(JSON.stringify({...fixture.importPayload,school}));
  assert.equal(unknownSchool.school.id,null,"unknown source school ID must remain absent");
  assert.equal(unknownSchool.school.name,null,"missing school name waits for preview confirmation");
  assert.equal(unknownSchool.key,null,"unknown school ID must not become a fabricated source identity");
}
assert.deepEqual(file.detectConflicts(parsed.meetings),{groupCount:2,meetingCount:5,groups:[[0,1],[2,3,4]]});
assert.deepEqual(file.detectConflicts([{...parsed.meetings[0],weeks:[1]},{...parsed.meetings[1],weeks:[2]}]),{groupCount:0,meetingCount:0,groups:[]});
const base={courseName:"Information Security",weekday:1,startPeriod:1,endPeriod:2,weeks:[1,2],teacher:"Teacher A",locationRaw:"Room A"};
const duplicatePayload={...fixture.importPayload,meetings:[base,{...base,courseName:" information  security ",teacher:" teacher a "},{...base,weekday:2},{...base,startPeriod:2,endPeriod:3,weeks:[2,3]}]};
const duplicateParsed=file.parseText(JSON.stringify(duplicatePayload));
assert.equal(duplicateParsed.meetings.length,3,"identical AI rows must not persist twice");
assert.equal(duplicateParsed.diagnostics.exactDuplicateCount,1);
assert.equal(file.detectDuplicateMeetings(duplicateParsed.meetings).length,1,"partially overlapping weeks and periods need review");
assert.equal(file.detectDuplicateMeetings(duplicateParsed.meetings).some(pair=>pair.left===0&&pair.right===1),false,"same course on a different day remains valid");
assert.throws(()=>file.parseText(JSON.stringify({...fixture.importPayload,meetings:[{...base,weeks:[]}]})),/缺少周次/);
assert.throws(()=>file.parseText(JSON.stringify({...fixture.importPayload,meetings:[{...base,weekday:8}]})),/星期/);
for(const weekday of [null,"未确定",undefined]){
  const meeting={...base,weekday};
  if(weekday===undefined)delete meeting.weekday;
  assert.throws(()=>file.parseText(JSON.stringify({...fixture.importPayload,meetings:[meeting]})),/星期/,"unresolved weekday must never pass Course Schema validation");
}
const shifted=file.parseText(JSON.stringify(columnShift.aiOutputWithWeekdayError));
assert.equal(shifted.meetings.length,2,"a range-valid weekday error is structurally valid JSON");
assert.equal(file.detectConflicts(shifted.meetings).groupCount,1,"a wrong weekday creates a false internal conflict");
const geometryCorrected=shifted.meetings.map((meeting,index)=>({...meeting,weekday:columnShift.sourceGrid.blocks[index].physicalColumn}));
assert.equal(file.detectConflicts(geometryCorrected).groupCount,0,"physical-column correction resolves the synthetic false conflict");
const alphaBetaGamma=multiColumn.sourceBlocks.map(block=>({courseName:block.name,weekday:block.physicalWeekday,startPeriod:block.startPeriod,endPeriod:block.endPeriod,weeks:block.weeks,teacher:null,locationRaw:null,isAdjusted:false}));
const falseWeekdays=alphaBetaGamma.map(row=>({...row,weekday:1}));
assert.equal(file.detectConflicts(alphaBetaGamma).groupCount,0,"three physical columns have no genuine time overlap");
assert.equal(file.detectConflicts(falseWeekdays).groupCount,1,"reading-order weekday 1 concentrates unrelated courses into a false conflict group");
assert.equal(file.detectConflicts([{...base,weekday:1},{...base,weekday:2}]).groupCount,0,"CASE 1: different weekdays are independent");
assert.equal(file.detectConflicts([{...base,courseName:"Alpha"},{...base,courseName:"Beta"}]).groupCount,1,"CASE 2: exact overlap conflicts");
assert.equal(file.detectConflicts([{...base,courseName:"Alpha",startPeriod:1,endPeriod:4},{...base,courseName:"Beta",startPeriod:3,endPeriod:6}]).groupCount,1,"CASE 3: partial period overlap conflicts");
assert.equal(file.detectConflicts([{...base,weeks:[1]},{...base,weeks:[2]}]).groupCount,0,"CASE 4: disjoint weeks do not conflict");
assert.equal(file.detectConflicts([{...base,courseName:"Alpha"},{...base,courseName:"Beta",weeks:[2]}]).groupCount,1,"CASE 7: misclassified weekday is import-internal conflict");
const existingCourse={courseId:"course:synthetic",title:"Stored Course",weekday:1,startPeriod:1,endPeriod:2,weeks:[1,2],location:"Example Room",sourceType:"manual"};
assert.equal(file.detectExistingConflicts([{...base,courseName:"Incoming"}],[existingCourse]).length,1,"CASE 8: incoming-vs-existing overlap is separate");
assert.equal(file.detectExistingConflicts([{...base,courseName:"Incoming"}],[{...existingCourse,weekday:2}]).length,0,"different existing weekday is safe");
assert.equal(file.detectExistingConflicts([{...base,courseName:"Incoming"}],[{...existingCourse,weekday:2}],[{courseId:existingCourse.courseId,fields:{weekday:1}}]).length,1,"effective existing override participates in conflict review");
const exactStored={...existingCourse,title:" Information  Security ",teacher:" teacher a ",location:" room a "};
let classified=file.classifyExistingMeetings([base],[exactStored]);
assert.equal(classified.exactDuplicates.length,1,"semantic existing duplicate is classified before overlap");
assert.equal(classified.conflicts.length,0,"semantic existing duplicate is not also a time conflict");
classified=file.classifyExistingMeetings([{...base,weeks:[1,2,3]}],[exactStored]);
assert.equal(classified.exactDuplicates.length,0,"partial week overlap is not an exact duplicate");
assert.equal(classified.conflicts.length,1,"partial week overlap remains a time conflict");
assert.equal(file.classifyExistingMeetings([{...base,locationRaw:"Room B"}],[exactStored]).conflicts.length,1,"different location remains a conflict");
assert.equal(file.classifyExistingMeetings([{...base,teacher:"Teacher B"}],[exactStored]).conflicts.length,1,"different teacher remains a conflict");
const denseValid=[];for(let weekday=1;weekday<=7;weekday++)for(let period=1;period<=6;period++)denseValid.push({...base,courseName:`Course ${weekday}-${period}`,weekday,startPeriod:period,endPeriod:period,weeks:period%2?[1,3,5,7,9]:[2,4,6,8,10]});
assert.equal(file.detectConflicts(denseValid).groupCount,0,"CASE 17: dense valid multi-day timetable must not produce false conflicts");
const prompt=fs.readFileSync(path.join(__dirname,"../app/assets/timetable/clipboard-import.js"),"utf8");
for(const part of ["anyclass-json-prompt-v5-cell-evidence-locked","表格几何结构","列标题及从左到右的物理位置","单元格/物理列","只根据该列上方的星期标题赋值 weekday","逐一交叉核对","PDF 文本顺序绝不能覆盖","OCR/PDF 文本提取顺序","内部逐条自检","异常集中在同一个星期","内部时间重叠是否多得不合理","同一个视觉单元格是否被提取两次","不能为消除冲突而擅自改动星期","无法确定课程块的物理星期列时","当前导入格式不能表示","不要悄悄省略该块而输出不完整 JSON","startPeriod","endPeriod","isAdjusted","学期第一周星期一","重叠","原图","Markdown","不要创建日历事件","不要仅按 courseName 合并","教师姓名当成地点","单周/双周","实验室 A","调课","先向我提问","只返回 JSON","单元格证据锁定","1-8节","1-10节","周次重新压缩","本部/敏行楼602","尚智楼","逐格逐字段核对"])assert(prompt.includes(part),`prompt missing ${part}`);
assert(prompt.includes("学校 ID 未显示或无法可靠确认时 school.id=null"));
assert(prompt.includes('"academicYear":"<已确认的YYYY-YYYY>"'));
assert(prompt.includes("原图和用户没有确认学年/学期时，必须先提问"));
assert(!prompt.includes('"academicYear":"2026-2027"'),"prompt must not provide a copyable academic-year default");
const practical={courseName:"工程实践",weekday:3,startPeriod:3,endPeriod:4,weeks:[1,3,5,7],teacher:"Instructor P",locationRaw:"Lab A",isAdjusted:false};
const realistic=file.parseText(JSON.stringify({...fixture.importPayload,meetings:[practical,{...practical,weeks:[2,4,6,8],locationRaw:"Lab B"},{...practical,weekday:5,startPeriod:7,endPeriod:8,weeks:[9],locationRaw:"Gym",isAdjusted:true}]}));
assert.equal(realistic.meetings.length,3,"different weeks, locations and adjusted sessions stay separate");
assert.equal(file.detectDuplicateMeetings(realistic.meetings).length,0);
assert(!/(?:Example Hidden Academy|Internal Example Institute)/i.test(JSON.stringify(fixture)));
console.log(JSON.stringify({fixture:"PUBLIC_SYNTHETIC",columns:7,meetingRows:parsed.meetings.length,conflictGroups:2,realisticSessions:realistic.meetings.length,weekdayMisclassificationConflictGroups:1,promptVersion:"v5",result:"PASS"}));
