"use strict";
const assert=require("node:assert/strict"),http=require("node:http"),fs=require("node:fs"),path=require("node:path");
const {chromium}=require("playwright"),site=path.resolve(__dirname,"../app");
const out=require("./local-artifacts").evidenceDirectory("clipboard-import-flow");
const executablePath=[path.join(process.env.LOCALAPPDATA||"","Google","Chrome","Application","chrome.exe"),path.join(process.env["PROGRAMFILES(X86)"]||"","Microsoft","Edge","Application","msedge.exe")].find(fs.existsSync);
const server=http.createServer((req,res)=>{let name=decodeURIComponent(new URL(req.url,"http://local").pathname);if(name.endsWith("/"))name+="index.html";const file=path.resolve(site,"."+name);if(!file.startsWith(site+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return}res.writeHead(200,{"content-type":file.endsWith(".js")?"application/javascript":file.endsWith(".css")?"text/css":"text/html"});res.end(fs.readFileSync(file))});
const fixture={schemaVersion:1,school:{id:"school-demo",name:"Example University"},semester:{academicYear:"2026-2027",term:"1"},meetings:[{courseName:"Course A",weekday:1,startPeriod:1,endPeriod:2,weeks:[1,2],teacher:null,locationRaw:null}]};
(async()=>{
  await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
  const browser=await chromium.launch({headless:true,executablePath});
  fs.mkdirSync(out,{recursive:true});
  try{
    const page=await browser.newPage({viewport:{width:390,height:844}});
    await page.goto(`http://127.0.0.1:${server.address().port}/import/?method=clipboard`);
    await page.locator("#clipboardRead").click();
    assert.match(await page.locator("#clipboardMessage").innerText(),/粘贴|剪贴板/);
    await page.evaluate(()=>Object.defineProperty(navigator,"clipboard",{configurable:true,value:{readText:async()=>{throw Error("DENIED")},writeText:async()=>{throw Error("DENIED")}}}));
    await page.locator("#clipboardRead").click();
    assert.match(await page.locator("#clipboardMessage").innerText(),/粘贴到下方文本框/);
    await page.locator("#clipboard-import").screenshot({path:path.join(out,"clipboard-read-denied-390.png")});
    await page.evaluate(value=>Object.defineProperty(navigator,"clipboard",{configurable:true,value:{readText:async()=>value,writeText:async()=>{}}}),JSON.stringify(fixture));
    await page.locator("#clipboardRead").click();
    await page.waitForFunction(()=>document.querySelector("#clipboardText").value.includes('"schemaVersion"'));
    assert.equal(await page.locator("#clipboardText").inputValue(),JSON.stringify(fixture));
    await page.locator("#clipboardText").fill("");
    await page.locator("#clipboardText").fill(JSON.stringify(fixture));
    await page.locator("#clipboardPreview").click();
    await page.locator("#filePreview:not([hidden])").waitFor();
    assert(await page.locator("#filePreview").isVisible());
    assert(await page.locator("#fileCalendarContext").isVisible());
    await page.locator("#fileSemesterStart").fill("2026-08-31");
    await page.locator("#fileSave").click();
    await page.waitForFunction(()=>/已保存/.test(document.querySelector("#fileSubmitMessage").textContent));
    await page.reload();
    await page.locator("#clipboardText").fill(JSON.stringify(fixture));
    await page.locator("#clipboardPreview").click();
    await page.locator("#filePreview:not([hidden])").waitFor();
    await page.locator("#fileSemesterStart").fill("2026-08-31");
    await page.locator("#fileSave").click();
    await page.waitForFunction(()=>/没有变化/.test(document.querySelector("#fileSubmitMessage").textContent));
    await page.locator(".clipboard-ai-help summary").click();
    await page.locator("#clipboardCopyPrompt").click();
    await page.waitForFunction(()=>/复制|手动/.test(document.querySelector("#clipboardPromptStatus").textContent));
    await page.locator("#clipboard-import").screenshot({path:path.join(out,"clipboard-prompt-copied-390.png")});
    assert.match(await page.locator("#clipboardPromptStatus").innerText(),/复制|手动/);
    const selectedBefore=await page.evaluate(async()=>(await AnyClassTimetableRepository.getActiveTimetable()).timetableId);
    const unknownIntoSelected={...fixture,school:{id:null,name:null},meetings:[{...fixture.meetings[0],courseName:"Course B"}]};
    await page.reload();
    await page.locator("#clipboardText").fill(JSON.stringify(unknownIntoSelected));
    await page.locator("#clipboardPreview").click();
    await page.locator("#filePreview:not([hidden])").waitFor();
    assert.equal(await page.locator("#fileSchoolName").inputValue(),"");
    assert.match(await page.locator("#fileImportTarget").innerText(),/将导入到/);
    await page.locator("#fileSchoolName").fill("示例大学");
    await page.locator("#fileSemesterStart").fill("2026-08-31");
    if(await page.locator("#fileConflictReview").isVisible()){
      await page.locator("#fileConflictDetails summary").click();
      for(const button of await page.locator("#fileConflictItems button").filter({hasText:"确认这是真实冲突，保留两者"}).all())await button.click();
      await page.locator("#fileConflictConfirm").check();
    }
    await page.locator("#fileSave").click();
    await page.waitForFunction(()=>/已保存/.test(document.querySelector("#fileSubmitMessage")?.textContent||""));
    const selectedAfter=await page.evaluate(async()=>(await AnyClassTimetableRepository.getActiveTimetable()).timetableId);
    assert.equal(selectedAfter,selectedBefore,"unknown school ID must not redirect the selected workspace");
    const unknown=await browser.newPage({viewport:{width:390,height:844}});
    await unknown.goto(`http://127.0.0.1:${server.address().port}/import/?method=clipboard`);
    await unknown.locator("#clipboardText").fill(JSON.stringify({...fixture,school:{id:null,name:null}}));
    await unknown.locator("#clipboardPreview").click();
    await unknown.locator("#filePreview:not([hidden])").waitFor();
    assert.equal(await unknown.locator("#fileSchoolName").inputValue(),"");
    assert.equal(await unknown.locator("#fileSave").isDisabled(),true);
    await unknown.locator("#fileSchoolName").fill("示例大学");
    await unknown.locator("#fileSemesterStart").fill("2026-08-31");
    await unknown.locator("#fileSave").click();
    await unknown.waitForFunction(()=>/已保存/.test(document.querySelector("#fileSubmitMessage").textContent));
    const stored=await unknown.evaluate(async()=>{
      const table=await AnyClassTimetableRepository.getActiveTimetable();
      const bundle=await AnyClassTimetableRepository.readTimetableBundle(table.timetableId);
      return {tableId:table.timetableId,schoolId:table.schoolId,schoolName:table.schoolName,sourceSchoolId:bundle.model.snapshots[0]?.school?.id,courses:bundle.model.courses.length};
    });
    assert.match(stored.tableId,/^timetable:user:/);
    assert.equal(stored.schoolId,null);
    assert.equal(stored.sourceSchoolId,null);
    assert.equal(stored.schoolName,"示例大学");
    assert.equal(stored.courses,1);
    await unknown.reload();
    await unknown.locator("#clipboardText").fill(JSON.stringify({...fixture,school:{id:null,name:null}}));
    await unknown.locator("#clipboardPreview").click();
    await unknown.locator("#filePreview:not([hidden])").waitFor();
    await unknown.locator("#fileSchoolName").fill("示例大学");
    await unknown.locator("#fileSemesterStart").fill("2026-08-31");
    await unknown.locator("#fileSave").click();
    await unknown.waitForFunction(()=>/课表没有变化/.test(document.querySelector("#fileSubmitMessage")?.textContent||""));
    assert.equal(await unknown.evaluate(async()=>(await AnyClassTimetableRepository.getActiveTimetable()).timetableId),stored.tableId,"unknown-ID reimport retains local timetable identity");
    console.log(JSON.stringify({clipboardDeniedFallback:"PASS",clipboardRead:"PASS",manualPaste:"PASS",schema4Save:"PASS",reload:"PASS",identicalReimport:"NO_CHANGE",promptCopy:"PASS",unknownSchoolId:"PASS"}));
  }finally{await browser.close();server.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
