"use strict";
const assert=require("node:assert/strict");
global.AnyClassPhaseB={idComponent:value=>Buffer.from(JSON.stringify(value)).toString("hex")};
global.AnyClassCourseModel=require("../app/assets/timetable/course-model.js");
const review=require("../app/assets/timetable/course-name-review.js");
let checks=0;const check=(value,label)=>{assert(value,label);checks++};
const meeting=(name,id,weekday=1)=>({courseName:name,sourceCourseId:id,sourceTeachingClassId:`meeting-${id}-${weekday}`,weekday,startPeriod:1,endPeriod:2,weeks:[1],teacher:null,locationRaw:null});
const dataset={key:"source:test",meetings:[meeting("信息安全","one"),meeting(" 信息安全 ","one",2),meeting("Information Security","two"),meeting("information security","three")]};
check(review.normalize("  Information   Security ")==="information security","conservative Latin normalization");
check(review.normalize("ÉCOLE")==="école","accented Latin letters are case insensitive");
check(review.normalize("信息-安全")!==review.normalize("信息安全"),"punctuation remains distinct");
check(global.AnyClassCourseModel.nameConflicts([{courseId:"legacy-a",title:"信息安全"},{courseId:"legacy-b",title:" 信息安全 "}]).length===1,"legacy distinct identities are detected without mutation");
check(review.groups(dataset.meetings).length===3,"one source course may have two meetings");
check(review.groups([{...meeting("Shared","a",1),sourceCourseId:undefined},{...meeting("Shared","b",2),sourceCourseId:undefined}]).length===1,"distinct meeting IDs do not imply distinct logical courses");
const first=review.plan(dataset.meetings);check(first.conflicts.length===1&&first.conflicts[0].kind==="INCOMING","distinct source courses with same name collide");
assert.throws(()=>review.apply(dataset,"target",new Map(),first),/IMPORT_COURSE_NAME_REVIEW_REQUIRED/);checks++;
const incoming=first.conflicts[0],merged=review.apply(dataset,"target",new Map([[incoming.incoming.key,{kind:"merge",targetGroupKey:incoming.other.key}]]),first);
check(merged.meetings.length===4,"merge retains every meeting");
check(merged.meetings[2].localLogicalCourseId===merged.meetings[3].localLogicalCourseId,"merge gives one logical owner");
const skipped=review.apply(dataset,"target",new Map([[incoming.incoming.key,{kind:"skip"}]]),first);
check(skipped.meetings.length===3,"skip removes only selected logical course");
const existing=[{courseId:"existing",title:"信息安全",sourceKey:"other",sourceRaw:{},timetableId:"target"}];
const collision=review.plan([meeting("信息安全","incoming")],existing,[],dataset.key);
check(collision.conflicts.length===1&&collision.conflicts[0].kind==="EXISTING","target course collision requires review");
const intoExisting=review.apply({key:dataset.key,meetings:[meeting("信息安全","incoming")]},"target",new Map([["source:incoming",{kind:"merge",logicalCourseId:"existing"}]]),collision);
check(intoExisting.meetings[0].localLogicalCourseId==="existing","explicit merge preserves existing logical owner");
assert.throws(()=>review.apply({key:dataset.key,meetings:[meeting("信息安全","incoming")]},"target",new Map([["source:incoming",{kind:"merge",logicalCourseId:"wrong"}]]),collision),/IMPORT_EXISTING_COURSE_NAME_STILL_DUPLICATED/);checks++;
check(review.plan([meeting("information security","one")],[],[],dataset.key).conflicts.length===0,"other timetable has independent name scope");
console.log(JSON.stringify({result:"COURSE_NAME_REVIEW_PASS",checks}));
