"use strict";
const assert=require("node:assert/strict"),http=require("node:http"),fs=require("node:fs"),path=require("node:path");
const evidence=require("./local-artifacts").evidenceDirectory("course-editing");
const {chromium}=require("playwright"),site=path.resolve(__dirname,"../app");
const server=http.createServer((req,res)=>{let pathname=decodeURIComponent(new URL(req.url,"http://local").pathname);if(pathname.endsWith("/"))pathname+="index.html";const file=path.resolve(site,"."+pathname);if(!file.startsWith(site)||!fs.existsSync(file)){res.writeHead(404);res.end("not found");return}res.writeHead(200,{"content-type":file.endsWith(".js")?"application/javascript":file.endsWith(".css")?"text/css":"text/html","cache-control":"no-store"});res.end(fs.readFileSync(file))});
const listen=()=>new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
(async()=>{
  const deployedBase=process.env.ANYCLASS_BROWSER_BASE?.replace(/\/$/,"");
  if(!deployedBase)await listen();
  const executablePath=[path.join(process.env.LOCALAPPDATA||"","Google","Chrome","Application","chrome.exe"),path.join(process.env["PROGRAMFILES(X86)"]||"","Microsoft","Edge","Application","msedge.exe")].find(fs.existsSync);
  const browser=await chromium.launch({executablePath,headless:true,args:["--disable-background-networking"]});
  const context=await browser.newContext({viewport:{width:390,height:844}});
  await context.addInitScript(({now})=>{const NativeDate=Date;class FixedDate extends NativeDate{constructor(...args){super(...(args.length?args:[now]))}static now(){return new NativeDate(now).getTime()}}Object.defineProperty(window,"Date",{value:FixedDate})},{now:"2026-09-08T09:00:00+08:00"});
  const page=await context.newPage(),base=deployedBase||`http://127.0.0.1:${server.address().port}`;
  let assertions=0;const check=(value,label)=>{assert(value,label);assertions++};
  try{
    await page.goto(base+"/timetable/");
    await page.addScriptTag({url:"/assets/timetable/ics-generator.js"});
    const seeded=await page.evaluate(async()=>{
      const profile=AnyClassSchoolProfileRegistry.get("school-demo");
      const fixture=term=>({key:`school-demo:2026-2027:${term}`,school:{id:"school-demo",name:"Example University",sourceSystem:"zhengfang-v9"},semester:{academicYear:"2026-2027",term},importedAt:"2026-09-01T00:00:00.000Z",fingerprint:`demo-${term}`,meetings:[{courseName:`Course ${term}`,teacher:"Teacher A",locationRaw:"Building A101",weekday:1,startPeriod:1,endPeriod:2,weeks:[1,2,3,4,5],notes:"Source note"}]});
      await AnyClassStorageV2.putLegacyAndMigrate(fixture("1"),profile);
      const first=await AnyClassTimetableRepository.getActiveTimetable();
      await AnyClassStorageV2.putLegacyAndMigrate(fixture("2"),profile);
      const second=(await AnyClassTimetableRepository.listTimetables()).find(row=>row.timetableId!==first.timetableId);
      const bundle=await AnyClassTimetableRepository.readActiveBundle();
      const dataset=await TimetableStorage.activeDataset();
      const ics=await TimetableIcs.generateFromEffective(dataset,dataset.__effectiveOccurrences,dataset.__runtimeProfile,{now:new Date("2026-09-01T00:00:00.000Z")});
      return {firstId:first.timetableId,secondId:second.timetableId,courseId:bundle.model.courses[0].courseId,source:bundle.model.courses[0],snapshot:bundle.model.snapshots[0],meeting:bundle.meetings[0],uids:[...ics.ics.matchAll(/(?:^|\r\n)UID:([^\r\n]+)/g)].map(match=>match[1]),occurrenceIds:dataset.__effectiveOccurrences.map(item=>item.occurrenceId)};
    });
    await page.evaluate(()=>refreshTimetableData());
    await page.waitForSelector("#app:not([hidden])");
    await page.locator(".mobile-course").first().click();
    check(await page.locator("#courseDialog").isVisible(),"detail opened");
    check((await page.locator("#dialogDetails").textContent()).includes("Teacher A"),"source detail resolved");
    await page.locator("#editCourse").click();
    check(await page.locator("#courseEditForm").isVisible(),"edit mode");
    await page.locator("#edit-teacher").fill("Teacher B");
    await page.locator("#cancelCourseEdit").click();
    check((await page.evaluate(id=>AnyClassTimetableRepository.readActiveBundle().then(bundle=>bundle.model.courseOverrides.find(row=>row.courseId===id)||null),seeded.courseId))===null,"cancel no mutation");
    await page.locator("#editCourse").click();
    await page.locator("#edit-teacher").fill("Teacher B");
    await page.locator("#courseEditForm button[type=submit]").click();
    await page.waitForFunction(()=>document.querySelector("#courseDetailView")&&!document.querySelector("#courseDetailView").hidden);
    const partial=await page.evaluate(id=>AnyClassTimetableRepository.readActiveBundle().then(bundle=>bundle.model.courseOverrides.find(row=>row.courseId===id)),seeded.courseId);
    check(JSON.stringify(partial.fields)===JSON.stringify({teacher:"Teacher B"}),"partial override only changed field");
    check((await page.locator("#dialogDetails").textContent()).includes("Teacher B"),"detail updated");
    const after=await page.evaluate(()=>AnyClassTimetableRepository.readActiveBundle());
    check(JSON.stringify(after.model.courses[0].sourceRaw)===JSON.stringify(seeded.source.sourceRaw),"sourceRaw immutable");
    check(JSON.stringify(after.model.courses[0])===JSON.stringify(seeded.source),"imported Course immutable");
    check(JSON.stringify(after.model.snapshots[0])===JSON.stringify(seeded.snapshot),"snapshot immutable");
    check(JSON.stringify(after.meetings[0])===JSON.stringify(seeded.meeting),"BaseMeeting immutable");
    check(after.model.courses[0].courseId===seeded.courseId,"course identity stable");
    await page.locator("#editCourse").click();
    await page.getByRole("button",{name:"恢复教师原值"}).click();
    await page.locator("#courseEditForm button[type=submit]").click();
    await page.waitForFunction(()=>document.querySelector("#courseDetailView")&&!document.querySelector("#courseDetailView").hidden);
    check((await page.evaluate(()=>AnyClassTimetableRepository.readActiveBundle())).model.courseOverrides.length===0,"restore deletes empty override");
    await page.locator("#editCourse").click();
    await page.locator("#edit-title").fill("  Edited Course  ");
    await page.locator("#edit-teacher").fill("Teacher B");
    await page.locator("#edit-location").fill("Building B202");
    await page.locator("#edit-notes").fill("Edited note");
    await page.locator("#edit-weekday").selectOption("2");
    await page.locator("#edit-startPeriod").selectOption("2");
    await page.locator("#edit-endPeriod").selectOption("3");
    await page.locator("#courseEditForm button[type=submit]").click();
    await page.waitForFunction(()=>document.querySelector("#courseDetailView")&&!document.querySelector("#courseDetailView").hidden);
    const edited=await page.evaluate(async()=>{const bundle=await AnyClassTimetableRepository.readActiveBundle(),dataset=await TimetableStorage.activeDataset();return {override:bundle.model.courseOverrides[0],activeId:(await AnyClassTimetableRepository.getActiveTimetable()).timetableId,first:dataset.__effectiveOccurrences[0]}});
    check(edited.override.fields.title==="Edited Course"&&edited.override.fields.teacher==="Teacher B"&&edited.override.fields.location==="Building B202"&&edited.override.fields.weekday===2&&edited.override.fields.startPeriod===2&&edited.override.fields.endPeriod===3&&edited.override.fields.notes==="Edited note","all editable scalar fields");
    check(edited.first.startTime!==undefined&&edited.first.endTime!==undefined,"effective period time derived");
    check(edited.activeId===seeded.firstId,"active unchanged");
    const identity=await page.evaluate(async()=>{const dataset=await TimetableStorage.activeDataset(),ics=await TimetableIcs.generateFromEffective(dataset,dataset.__effectiveOccurrences,dataset.__runtimeProfile,{now:new Date("2026-09-01T00:00:00.000Z")});return {uids:[...ics.ics.matchAll(/(?:^|\r\n)UID:([^\r\n]+)/g)].map(match=>match[1]),occurrenceIds:dataset.__effectiveOccurrences.map(item=>item.occurrenceId),summary:ics.ics.includes("SUMMARY:Edited Course")}});
    check(JSON.stringify(identity.uids)===JSON.stringify(seeded.uids),"UID set and order stable for unchanged weeks");
    check(JSON.stringify(identity.occurrenceIds)===JSON.stringify(seeded.occurrenceIds),"occurrence identities stable for weekday/period/text edits");
    check(identity.summary,"ICS effective title");
    await page.locator("#editCourse").click();
    await page.getByRole("button",{name:"恢复教师原值"}).click();
    await page.locator("#courseEditForm button[type=submit]").click();
    await page.waitForFunction(()=>document.querySelector("#courseDetailView")&&!document.querySelector("#courseDetailView").hidden);
    const oneRestored=await page.evaluate(()=>AnyClassTimetableRepository.readActiveBundle().then(bundle=>bundle.model.courseOverrides[0].fields));
    check(!Object.hasOwn(oneRestored,"teacher")&&oneRestored.title==="Edited Course","single-field restore preserves other overrides");
    const isolated=await page.evaluate(id=>AnyClassTimetableRepository.readTimetableBundle(id).then(bundle=>({course:bundle.model.courses[0],overrides:bundle.model.courseOverrides,snapshots:bundle.model.snapshots})),seeded.secondId);
    check(isolated.overrides.length===0&&isolated.course.title==="Course 2"&&isolated.snapshots.length===1,"second timetable isolated");
    await page.reload();await page.addScriptTag({url:"/assets/timetable/ics-generator.js"});await page.waitForSelector("#app:not([hidden])");
    check((await page.locator(".mobile-course").first().textContent()).includes("Edited Course"),"reload retains override");
    await page.locator(".mobile-course").first().click();
    await page.locator("#editCourse").click();
    await page.locator("#edit-title").fill("   ");
    await page.locator("#courseEditForm button[type=submit]").click();
    await page.waitForSelector("#courseEditError:not([hidden])");
    check((await page.locator("#courseEditError").textContent()).includes("不能为空"),"empty title rejected");
    await page.locator("#cancelCourseEdit").click();
    const rejected=await page.evaluate(async id=>{const repo=AnyClassTimetableRepository,bundle=await repo.readActiveBundle(),course=bundle.model.courses.find(row=>row.courseId===id),override=bundle.model.courseOverrides.find(row=>row.courseId===id),draft={...AnyClassCourseEditing.resolved(course,override)};let weeks=false,weekRange=false,period=false,weekday=false;try{await repo.saveCourseOverride(id,{...draft,weeks:[]})}catch(_){weeks=true}try{await repo.saveCourseOverride(id,{...draft,weeks:[bundle.term.totalWeeks+1]})}catch(_){weekRange=true}try{await repo.saveCourseOverride(id,{...draft,startPeriod:3,endPeriod:2})}catch(_){period=true}try{await repo.saveCourseOverride(id,{...draft,weekday:8})}catch(_){weekday=true}const after=await repo.readActiveBundle();return {weeks,weekRange,period,weekday,unchanged:JSON.stringify(after.model.courseOverrides)===JSON.stringify(bundle.model.courseOverrides)}},seeded.courseId);
    check(rejected.weeks&&rejected.weekRange&&rejected.period&&rejected.weekday&&rejected.unchanged,"invalid weeks/periods/weekday rollback");
    await page.locator("#editCourse").click();
    await page.locator('[data-edit-field="weeks"] input[value="1"]').uncheck();
    await page.locator("#courseEditForm button[type=submit]").click();
    await page.waitForFunction(()=>document.querySelector("#courseDetailView")&&!document.querySelector("#courseDetailView").hidden);
    const weekEdit=await page.evaluate(async()=>{const dataset=await TimetableStorage.activeDataset(),ics=await TimetableIcs.generateFromEffective(dataset,dataset.__effectiveOccurrences,dataset.__runtimeProfile,{now:new Date("2026-09-01T00:00:00.000Z")});return {weeks:dataset.__effectiveOccurrences.map(item=>item.week),uids:[...ics.ics.matchAll(/(?:^|\r\n)UID:([^\r\n]+)/g)].map(match=>match[1])}});
    check(weekEdit.weeks.length===4&&!weekEdit.weeks.includes(1),"week edit removes one occurrence");
    check(weekEdit.uids.every(uid=>seeded.uids.includes(uid)),"surviving weeks retain original UIDs");
    await page.locator("#editCourse").click();
    const weekField=page.locator('[data-edit-field="weeks"]');
    check(await page.getByRole("button",{name:"选择范围"}).count()===0,"competing range selector removed");
    await weekField.getByRole("button",{name:"清空"}).click();
    check((await weekField.locator(".course-edit-week-summary").textContent()).includes("未选择周次"),"clear updates summary");
    for(const week of [1,2,4,5])await weekField.locator(`input[value="${week}"]`).check();
    check((await weekField.locator(".course-edit-week-summary").textContent()).includes("1–2、4–5周"),"selected-week summary compacts contiguous weeks");
    await weekField.getByRole("button",{name:"全选"}).click();
    check(await weekField.locator("input:checked").count()===await weekField.locator("input").count(),"select all derives from one checkbox state");
    await weekField.getByRole("button",{name:"清空"}).click();
    for(const week of [2,4])await weekField.locator(`input[value="${week}"]`).check();
    check(await weekField.locator("input:checked").count()===2,"individual toggles work after clear");
    await page.locator("#cancelCourseEdit").click();
    await page.goto(base+"/today/");await page.waitForSelector("#app:not([hidden])");
    check((await page.locator("#app").textContent()).includes("Edited Course"),"Today reflects edited course");
    await page.goto(base+"/export/");await page.waitForSelector("#app:not([hidden])");
    check((await page.locator("#eventCount").textContent()).trim()==="4","Export reflects edited week count");
    for(const width of [390,430,1024,1440])for(const dark of [false,true]){
      await page.setViewportSize({width,height:width<700?844:900});
      await page.emulateMedia({colorScheme:dark?"dark":"light"});
      await page.goto(base+"/timetable/");await page.waitForSelector("#app:not([hidden])");
      await page.locator(width<700?".mobile-course":".course-card").first().click();
      const detail=await page.locator("#courseDialog").boundingBox();
      check(detail.x>=0&&detail.x+detail.width<=width+1,`detail bounds ${width} ${dark}`);
      await page.locator("#editCourse").click();
      if(width===390&&dark)await page.screenshot({path:path.join(evidence,"anyclass-phase2a-editor-mobile-dark.png")});
      if(width===1440&&!dark)await page.screenshot({path:path.join(evidence,"anyclass-phase2a-editor-desktop-light.png")});
      const restores=await page.locator(".restore-field:visible").evaluateAll(nodes=>nodes.map(node=>({tag:node.tagName,decoration:getComputedStyle(node).textDecorationLine})));
      check(restores.length>0&&restores.every(item=>item.tag==="BUTTON"&&item.decoration==="none"),`restore text buttons ${width} ${dark}`);
      await page.locator(".restore-field:visible").first().hover();
      check(await page.locator(".restore-field:visible").first().evaluate(node=>getComputedStyle(node).textDecorationLine)==="none",`restore hover no underline ${width} ${dark}`);
      await page.locator(".restore-field:visible").first().focus();
      check(await page.locator(".restore-field:visible").first().evaluate(node=>getComputedStyle(node).outlineStyle)!=="none",`restore keyboard focus ${width} ${dark}`);
      const edit=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,dialog:document.querySelector("#courseDialog").getBoundingClientRect().right}));
      check(edit.scroll<=edit.client&&edit.dialog<=edit.client+1,`editor bounds ${width} ${dark}`);
      check(await page.locator("#edit-title").isVisible(),`editor visible ${width} ${dark}`);
      await page.locator("#cancelCourseEdit").click();
    }
    await page.setViewportSize({width:390,height:844});
    await page.goto(base+"/timetable/");await page.addScriptTag({url:"/assets/timetable/ics-generator.js"});await page.waitForSelector("#app:not([hidden])");
    await page.locator(".mobile-course").first().click();
    await page.locator("#editCourse").click();
    for(const field of ["课程名称","地点","备注","星期","上课周次","开始节次","结束节次"]){
      const restore=page.getByRole("button",{name:`恢复${field}原值`});
      if(await restore.isVisible())await restore.click();
    }
    await page.locator("#courseEditForm button[type=submit]").click();
    await page.waitForFunction(()=>document.querySelector("#courseDetailView")&&!document.querySelector("#courseDetailView").hidden);
    const restored=await page.evaluate(async()=>{const bundle=await AnyClassTimetableRepository.readActiveBundle(),dataset=await TimetableStorage.activeDataset(),ics=await TimetableIcs.generateFromEffective(dataset,dataset.__effectiveOccurrences,dataset.__runtimeProfile,{now:new Date("2026-09-01T00:00:00.000Z")});return {overrides:bundle.model.courseOverrides.length,uids:[...ics.ics.matchAll(/(?:^|\r\n)UID:([^\r\n]+)/g)].map(match=>match[1])}});
    check(restored.overrides===0,"all fields restored deletes override record");
    check(JSON.stringify(restored.uids)===JSON.stringify(seeded.uids),"restored source UID order");
    const weekContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),weekPage=await weekContext.newPage();
    try{
      await weekPage.goto(base+"/timetable/");
      await weekPage.evaluate(async()=>{
        const profile=AnyClassSchoolProfileRegistry.get("school-demo");
        await AnyClassStorageV2.putLegacyAndMigrate({key:"school-demo:2026-2027:1",school:{id:"school-demo",name:"Example University",sourceSystem:"zhengfang-v9"},semester:{academicYear:"2026-2027",term:"1"},importedAt:"2026-09-01T00:00:00.000Z",fingerprint:"week-grid-18",meetings:[{courseName:"Week Grid Course",teacher:"Example Teacher",locationRaw:"Example Room",weekday:1,startPeriod:1,endPeriod:2,weeks:Array.from({length:18},(_,index)=>index+1)}]},profile);
      });
      await weekPage.reload();await weekPage.waitForSelector("#app:not([hidden])");await weekPage.locator(".mobile-course").first().click();await weekPage.locator("#editCourse").click();
      const weeks=weekPage.locator('[data-edit-field="weeks"]');
      check(await weeks.locator("input").count()>=18,"week grid supports 18-week term");
      await weeks.getByRole("button",{name:"清空"}).tap();
      const selection=[1,2,4,5,6,7,8,9,10,13,14,16,17,18];
      for(const week of selection)await weeks.locator(`input[value="${week}"]`).check();
      check((await weeks.locator(".course-edit-week-summary").textContent()).includes("1–2、4–10、13–14、16–18周"),"exact requested 18-week summary");
      await weekPage.locator("#courseEditForm button[type=submit]").tap();await weekPage.waitForFunction(()=>!document.querySelector("#courseEditForm")?.offsetParent);
      const stored=await weekPage.evaluate(async()=>{const bundle=await AnyClassTimetableRepository.readActiveBundle(),course=bundle.model.courses[0],override=bundle.model.courseOverrides.find(row=>row.courseId===course.courseId);return AnyClassCourseEditing.resolved(course,override).weeks});
      check(JSON.stringify(stored)===JSON.stringify(selection),"week grid saves exact selected weeks");
      await weekPage.reload();await weekPage.waitForSelector("#app:not([hidden])");await weekPage.locator(".mobile-course").first().click();await weekPage.locator("#editCourse").click();
      check((await weekPage.locator('[data-edit-field="weeks"] .course-edit-week-summary').textContent()).includes("1–2、4–10、13–14、16–18周"),"saved week grid reloads exact selection");
    }finally{await weekContext.close()}
    console.log(JSON.stringify({result:"COURSE_EDITING_BROWSER_PASS",assertions}));
  }finally{await context.close();await browser.close();if(server.listening)server.close()}
})().catch(error=>{console.error(error);process.exitCode=1;if(server.listening)server.close()});
