"use strict";
const assert = require("node:assert/strict");
const engine = require("../app/assets/timetable/phaseb-engine.js");
const courseModel = require("../app/assets/timetable/course-model.js");
globalThis.AnyClassPhaseB = engine;
globalThis.AnyClassCourseResolver = require("../app/assets/timetable/course-resolver.js");
const effective = require("../app/assets/timetable/effective-occurrences.js");

const config = {semesterStartDate:"2026-09-07",timezone:"Asia/Shanghai",periodTimes:{1:{start:"08:00",end:"08:45"},2:{start:"08:55",end:"09:40"},3:{start:"10:00",end:"10:45"},4:{start:"10:55",end:"11:40"}},profileVersion:"test",adapterId:"test",adapterVersion:"test"};
const dataset = {key:"school:test:2026:1",school:{id:"test",name:"测试学校"},semester:{academicYear:"2026",term:"1"},meetings:[{courseName:"源课程",teacher:"源教师",locationRaw:"A101",weekday:1,startPeriod:1,endPeriod:2,weeks:[1,2],campus:"源校区",notes:"源备注"}]};
const graph = engine.convertV1Dataset(dataset, config, "2026-09-01T00:00:00.000Z");
const built = courseModel.build(dataset, graph), baselineModel = {...built,snapshots:[built.snapshot]}, source = baselineModel.courses[0], sourceCopy = structuredClone(source);
const context = {semesterStartDate:graph.term.semesterStartDate,timezone:graph.term.timezone,periodTimes:graph.term.periodTimes};
const sourceOnly = effective.build({...baselineModel,courseOverrides:[],occurrenceOverrides:[],scheduleOverrides:[]}, context);
assert.equal(sourceOnly.length, 2);
assert.equal(sourceOnly[0].location, "A101");
assert.equal(sourceOnly[0].startTime, "08:00");
assert.equal(sourceOnly[0].uidIdentity.locationRaw, "A101");

const courseOverride = {courseId:source.courseId,fields:{title:"改名课程",teacher:"课程教师",school:{id:"other",name:"覆盖学校"},campus:"覆盖校区",location:"A201",notes:"覆盖备注",weekday:2,weeks:[1],startPeriod:3,endPeriod:4}};
const occurrenceId = `occurrence:${engine.idComponent([source.sourceMeetingId,"2026-09-08"])}`;
const occurrenceOverride = {occurrenceId,courseId:source.courseId,fields:{location:"A301",teacher:"单次教师",startPeriod:2,endPeriod:3}};
const courseOnly = effective.build({...baselineModel,courseOverrides:[courseOverride],occurrenceOverrides:[],scheduleOverrides:[]}, context);
assert.equal(courseOnly.length, 1);
assert.equal(courseOnly[0].location, "A201");
assert.equal(courseOnly[0].title, "改名课程");
assert.equal(courseOnly[0].teacher, "课程教师");
assert.equal(courseOnly[0].school.name, "覆盖学校");
assert.equal(courseOnly[0].campus, "覆盖校区");
assert.equal(courseOnly[0].notes, "覆盖备注");
assert.equal(courseOnly[0].startTime, "10:00");
assert.equal(courseOnly[0].endTime, "11:40");
const occurrenceOnly = effective.build({...baselineModel,courseOverrides:[courseOverride],occurrenceOverrides:[occurrenceOverride],scheduleOverrides:[]}, context);
assert.equal(occurrenceOnly[0].location, "A301");
assert.equal(occurrenceOnly[0].teacher, "单次教师");
assert.equal(occurrenceOnly[0].startTime, "08:55");
assert.equal(occurrenceOnly[0].endTime, "10:45");
assert.equal(occurrenceOnly[0].uidIdentity.locationRaw, "A101");
const cancelled = effective.build({...baselineModel,courseOverrides:[courseOverride],occurrenceOverrides:[{occurrenceId,courseId:source.courseId,fields:{cancelled:true}}],scheduleOverrides:[]}, context);
assert.equal(cancelled.length, 0);
assert.deepEqual(source, sourceCopy);
assert.throws(()=>effective.build({...baselineModel,courseOverrides:[],occurrenceOverrides:[{occurrenceId:"occurrence:orphan",courseId:source.courseId,fields:{location:"x"}}],scheduleOverrides:[]},context),/ORPHANED_OCCURRENCE_OVERRIDE/);
console.log(JSON.stringify({sourceOnly:"PASS",courseOverride:"PASS",occurrenceOverride:"PASS",cancellation:"PASS",precedence:"PASS",sourceImmutability:"PASS",uidIdentityFrozen:"PASS",result:"PASS"},null,2));
