"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const app=path.resolve(__dirname,"../app/assets/timetable"),fixture=path.resolve(__dirname,"../../private-baseline/phase-b-v1-migration.json");
if(!fs.existsSync(fixture))throw new Error("PRIVATE_CANONICAL_FIXTURE_REQUIRED");
const engine=require(path.join(app,"phaseb-engine.js"));globalThis.AnyClassPhaseB=engine;
const modelApi=require(path.join(app,"course-model.js"));globalThis.AnyClassCourseResolver=require(path.join(app,"course-resolver.js"));
const effectiveApi=require(path.join(app,"effective-occurrences.js")),ics=require(path.join(app,"ics-generator.js")),config=require(path.join(app,"school-config.js")).demo;
const dataset=JSON.parse(fs.readFileSync(fixture,"utf8")).payload.indexedDb.datasets[0],graph=engine.convertV1Dataset(dataset,config,"2026-09-17T00:00:00.000Z");
const model=modelApi.build(dataset,graph),effective=effectiveApi.build({...model,snapshots:[model.snapshot],courseOverrides:[],occurrenceOverrides:[],scheduleOverrides:[]},{semesterStartDate:graph.term.semesterStartDate,timezone:graph.term.timezone,periodTimes:graph.term.periodTimes});
const legacy=engine.finalOccurrences(graph),byId=new Map(effective.map(x=>[x.occurrenceId,x]));let differences=0;
const fields=["effectiveDate","startTime","endTime","timezone","courseName","teacher","location","adjusted"];
for(const old of legacy){const item=byId.get(old.finalOccurrenceId);if(!item){differences++;continue}const normalized={effectiveDate:item.effectiveDate,startTime:item.startTime,endTime:item.endTime,timezone:item.timezone,courseName:item.title,teacher:item.teacher||undefined,location:item.location||undefined,adjusted:item.adjusted};for(const field of fields)if(normalized[field]!==old[field])differences++;const base=graph.baseMeetings.find(x=>x.baseMeetingId===old.baseMeetingId);if(item.weekday!==base.recurrence.weekday||item.startPeriod!==base.time.startPeriod||item.endPeriod!==base.time.endPeriod)differences++;}
const uids=value=>(String(value).replace(/\r\n[ \t]/g,"").match(/(?:^|\r\n)UID:([^\r\n]+)/g)||[]).map(x=>x.replace(/^(?:\r\n)?UID:/,""));
(async()=>{const options={now:new Date("2026-09-17T00:00:00.000Z")},before=await ics.generateFromFinal(graph,config,options),after=await ics.generateFromEffective(dataset,effective,config,options);assert.equal(model.courses.length,29);assert.equal(engine.logicalOccurrences(graph).length,110);assert.equal(effective.length,110);assert.equal(after.generatedEvents,110);assert.equal(differences,0);assert.deepEqual(uids(after.ics),uids(before.ics));console.log(JSON.stringify({sourceCourses:29,logicalOccurrences:110,effectiveOccurrences:110,icsEvents:110,parityFields:["identity","week","date","weekday","startPeriod","endPeriod","startTime","endTime","title","teacher","location","adjusted","conflictInputs","uidInputs","uid"],parityDifferences:0,uidSet:"IDENTICAL",uidOrder:"IDENTICAL",result:"PASS"},null,2))})().catch(e=>{console.error(e);process.exit(1)});
