"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),os=require("node:os"),cp=require("node:child_process");
const root=path.resolve(__dirname,".."),out=fs.mkdtempSync(path.join(os.tmpdir(),"anyclass-client-channels-"));
const run=cp.spawnSync(process.execPath,[path.join(root,"tools/build-import-clients.js"),out],{encoding:"utf8"});assert.equal(run.status,0,run.stderr);
const read=channel=>JSON.parse(fs.readFileSync(path.join(out,channel,"manifest.json"),"utf8")),beta=read("beta"),stable=read("stable");
assert.equal(beta.bookmark.targetOrigin,"https://beta.anyclass.heyaaron.asia");assert.equal(stable.bookmark.targetOrigin,"https://anyclass.heyaaron.asia");
assert.equal(beta.shortcut.targetImportUrl,"https://beta.anyclass.heyaaron.asia/import/?method=file");assert.equal(stable.shortcut.targetImportUrl,"https://anyclass.heyaaron.asia/import/?method=file");
assert.equal(beta.shortcut.iCloudUrl,"https://www.icloud.com/shortcuts/2d1a3282109345918058db7cf1efd818");assert.equal(stable.shortcut.iCloudUrl,"https://www.icloud.com/shortcuts/8b151aa3c24441c3b87c6f2b85fa5f37");
assert.equal(beta.channel,"beta");assert.equal(stable.channel,"stable");assert.equal(beta.importProtocol,"timetable-import-v1");assert.equal(beta.storageSchema,4);assert.equal(beta.normalizedImportSchema,1);
const bb=fs.readFileSync(path.join(out,"beta/bookmarklet.txt"),"utf8"),sb=fs.readFileSync(path.join(out,"stable/bookmarklet.txt"),"utf8");
const betaShortcut=fs.readFileSync(path.join(out,"beta/ios-shortcut-parser.js"),"utf8"),stableShortcut=fs.readFileSync(path.join(out,"stable/ios-shortcut-parser.js"),"utf8");
assert(bb.includes('channel:"beta"')&&bb.includes(beta.bookmark.targetOrigin)&&!bb.includes(stable.bookmark.targetOrigin));
assert(sb.includes('channel:"stable"')&&sb.includes(stable.bookmark.targetOrigin)&&!sb.includes(beta.bookmark.targetOrigin));
for(const value of ["jw.example.edu","school-demo","Example University"])assert(!betaShortcut.includes(value),`fixture placeholder leaked into Beta Shortcut: ${value}`);
assert(betaShortcut.includes('id: null')&&betaShortcut.includes('name: null'),"unknown school identity must remain null");
assert.equal(betaShortcut,stableShortcut,"Shortcut parser semantics must be shared byte-for-byte");
assert.equal(beta.shortcut.parserSha256,stable.shortcut.parserSha256,"Shortcut parser semantics must be shared");
assert.equal(stable.shortcut.stableICloudUrl,"https://www.icloud.com/shortcuts/8b151aa3c24441c3b87c6f2b85fa5f37");assert.equal(beta.shortcut.stableICloudUrl,null);
assert.equal(beta.shortcut.published,true);assert.equal(stable.shortcut.published,true);
console.log(JSON.stringify({result:"IMPORT_CLIENT_CHANNELS_PASS",bookmarkVersion:beta.bookmark.version,shortcutVersion:beta.shortcut.version,protocol:beta.importProtocol,schema:beta.storageSchema,parserParity:"IDENTICAL"},null,2));
