"use strict";

const assert=require("node:assert/strict");
const fs=require("node:fs");
const http=require("node:http");
const path=require("node:path");
const {chromium}=require("playwright");
const {evidenceDirectory}=require("./local-artifacts");

const root=path.resolve(__dirname,"../app");
const evidence=evidenceDirectory("issue030-motion-coverage");
const externalBase=String(process.env.ANYCLASS_TEST_BASE||"").replace(/\/$/,"");
const executablePath=[path.join(process.env.LOCALAPPDATA||"","Google","Chrome","Application","chrome.exe"),path.join(process.env["PROGRAMFILES(X86)"]||"","Microsoft","Edge","Application","msedge.exe")].find(fs.existsSync);
const mime=file=>file.endsWith(".js")?"application/javascript":file.endsWith(".css")?"text/css":file.endsWith(".svg")?"image/svg+xml":file.endsWith(".png")?"image/png":file.endsWith(".json")?"application/json":"text/html";
const server=http.createServer((request,response)=>{let name=decodeURIComponent(new URL(request.url,"http://local").pathname);if(name.endsWith("/"))name+="index.html";const file=path.resolve(root,"."+name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){response.writeHead(404);response.end();return}response.writeHead(200,{"content-type":mime(file),"cache-control":"no-store"});response.end(fs.readFileSync(file))});
const fixture={schemaVersion:1,school:{id:null,name:"Synthetic Motion University"},semester:{academicYear:"2026-2027",term:"1"},timetableName:"Motion Coverage",meetings:[{courseName:"Course Alpha",teacher:"Teacher A",locationRaw:"Room A",weekday:1,startPeriod:1,endPeriod:2,weeks:[1,2,3,4,5,6,7,8],isAdjusted:false},{courseName:"Course Beta",teacher:"Teacher B",locationRaw:"Room B",weekday:3,startPeriod:3,endPeriod:4,weeks:[1,2,3,4,5,6,7,8],isAdjusted:false}]};

(async()=>{
  fs.mkdirSync(evidence,{recursive:true});
  if(!externalBase)await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
  const base=externalBase||`http://127.0.0.1:${server.address().port}`;
  const browser=await chromium.launch({executablePath,headless:true,args:["--disable-background-networking","--disable-features=OverlayScrollbar"]});
  let assertions=0;const check=(value,label)=>{assert(value,label);assertions++};const matrix=[];
  const freezeWelcome=async(page,time)=>page.locator("[data-onboarding-primary]").evaluate((node,value)=>{const animation=node.getAnimations().find(item=>item.animationName==="anyclass-welcome-cta-attention");animation.pause();animation.currentTime=value},time);
  const welcomeState=page=>page.locator("[data-onboarding-primary]").evaluate(node=>{const style=getComputedStyle(node),rect=node.getBoundingClientRect();return{active:document.activeElement===node,focus:node.matches(":focus"),focusVisible:node.matches(":focus-visible"),outlineColor:style.outlineColor,outlineStyle:style.outlineStyle,outlineWidth:style.outlineWidth,background:style.backgroundColor,shadow:style.boxShadow,opacity:style.opacity,transform:style.transform,animation:style.animationName,iterations:style.animationIterationCount,rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height}}});
  const seed=async page=>{await page.goto(`${base}/import/?method=file`);await page.locator("#fileInput").setInputFiles({name:"issue030.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(fixture))});await page.locator("#filePreview:not([hidden])").waitFor();await page.locator("#fileSemesterStart").fill("2026-08-31");await page.waitForFunction(()=>document.querySelector("#filePreview").dataset.importState==="PREVIEW_READY");await page.locator("#fileSave").click();await page.waitForFunction(()=>document.querySelector("#filePreview").dataset.importState==="SUCCESS")};
  try{
    const cases=[...(["light","dark"].flatMap(theme=>[390,430,768,1280].map(width=>({theme,width,height:width<700?844:900,mobile:width<700})))),{theme:"light",width:844,height:390,mobile:true,landscape:true}];
    for(const item of cases){
      const {theme,width,height,mobile}=item,label=`${theme}-${width}x${height}`;
      const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,colorScheme:theme});
      const page=await context.newPage(),errors=[];page.on("pageerror",error=>errors.push(String(error)));page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});
      await page.goto(`${base}/`);const dialog=page.locator("[data-onboarding-dialog][open]"),primary=page.locator("[data-onboarding-primary]");await primary.waitFor();
      check(await dialog.evaluate(node=>document.activeElement===node),`${label}: Welcome initially focuses its container, not the CTA`);
      await page.evaluate(()=>document.querySelector("[data-onboarding-primary]").addEventListener("click",event=>event.preventDefault(),{capture:true}));
      await primary.evaluate(node=>{node.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,pointerType:"touch",pointerId:7}));node.dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true}))});
      const touch=await welcomeState(page);check(!touch.active&&!touch.focus&&!touch.focusVisible,`${label}: touch activation leaves no persistent CTA focus ${JSON.stringify(touch)}`);
      await page.screenshot({path:path.join(evidence,`${label}-welcome-touch-after.png`)});
      await primary.evaluate(node=>{node.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,pointerType:"mouse",pointerId:8,button:0}));node.dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true,button:0}))});
      const mouse=await welcomeState(page);check(!mouse.active&&!mouse.focusVisible,`${label}: mouse activation leaves no persistent CTA focus`);
      await dialog.focus();await page.keyboard.press("Tab");await page.keyboard.press("Tab");const keyboard=await welcomeState(page);check(keyboard.active&&keyboard.focusVisible&&keyboard.outlineStyle!=="none"&&parseFloat(keyboard.outlineWidth)>=3,`${label}: Tab keyboard focus stays visible ${JSON.stringify(keyboard)}`);
      await page.keyboard.press("Enter");const enter=await welcomeState(page);check(enter.active&&enter.focusVisible,`${label}: Enter preserves keyboard focus visibility`);
      await page.locator("[data-complete-onboarding]").last().focus();await page.keyboard.press("Shift+Tab");const reverse=await welcomeState(page);check(reverse.active&&reverse.focusVisible,`${label}: Shift+Tab restores visible CTA focus`);
      await page.keyboard.press("Space");const space=await welcomeState(page);check(space.active&&space.focusVisible,`${label}: Space does not erase keyboard focus indication`);
      await primary.evaluate(async node=>{node.blur();await document.fonts.ready});await page.waitForFunction(()=>[...document.querySelector("[data-onboarding-dialog]").getAnimations({subtree:true})].filter(animation=>animation.animationName!=="anyclass-welcome-cta-attention").every(animation=>animation.playState==="finished"||animation.playState==="idle"));await freezeWelcome(page,0);const low=await welcomeState(page);await page.screenshot({path:path.join(evidence,`${label}-welcome-low.png`)});await freezeWelcome(page,950);const high=await welcomeState(page);await page.screenshot({path:path.join(evidence,`${label}-welcome-high.png`)});
      check(low.animation==="anyclass-welcome-cta-attention"&&low.iterations==="3",`${label}: Welcome keeps a finite three-cycle cue`);check(high.background!==low.background&&high.shadow!=="none"&&high.shadow!==low.shadow,`${label}: Welcome high point is visibly stronger ${JSON.stringify({low,high})}`);check(high.opacity===low.opacity&&high.transform===low.transform&&JSON.stringify(high.rect)===JSON.stringify(low.rect),`${label}: breathing preserves text opacity, transform, geometry, and hit target`);
      await page.evaluate(()=>localStorage.setItem("anyclass.onboardingCompleted","1"));await page.goto(`${base}/import/`);const fileMethod=page.locator('#chooseFile');await fileMethod.click();const methodPanel=page.locator('[data-import-panel="file"]');const methodMotion=await methodPanel.evaluate(node=>({className:node.className,animation:getComputedStyle(node).animationName,overflow:document.documentElement.scrollWidth>innerWidth+1}));check(methodMotion.className.includes("shell-content-refresh")&&methodMotion.animation==="shell-content-refresh"&&!methodMotion.overflow,`${label}: Import method switch has one scoped panel reveal`);await page.screenshot({path:path.join(evidence,`${label}-import-method-mid.png`)});await page.waitForTimeout(280);await page.screenshot({path:path.join(evidence,`${label}-import-method-after.png`)});
      if([390,1280].includes(width)&&!item.landscape){
        await seed(page);await page.goto(`${base}/timetable/`);await page.locator("#app:not([hidden])").waitFor();const target=mobile?page.locator("#mobileWeekList"):page.locator("#weekGrid");await target.screenshot({path:path.join(evidence,`${label}-week-before.png`)});await page.locator("#next").click();const weekMotion=await target.evaluate(node=>({animation:getComputedStyle(node).animationName,count:node.getAnimations().filter(animation=>animation.animationName==="shell-content-refresh").length}));check(weekMotion.animation==="shell-content-refresh"&&weekMotion.count===1,`${label}: week replacement uses exactly one container reveal ${JSON.stringify(weekMotion)}`);await target.screenshot({path:path.join(evidence,`${label}-week-mid.png`)});await page.waitForTimeout(280);await target.screenshot({path:path.join(evidence,`${label}-week-after.png`)});await page.locator("#next").click();await page.locator("#previous").click();await page.locator("#next").click();const rapid=await target.evaluate(node=>node.getAnimations().filter(animation=>animation.animationName==="shell-content-refresh").length);check(rapid<=1,`${label}: rapid week reversal does not queue animations`);
        const course=page.locator(mobile?".mobile-course":".course-card").first();await course.click();await page.locator("#courseDialog[open]").waitFor();await page.locator("#editCourse").click();const editMotion=await page.locator("#courseEditForm").evaluate(node=>getComputedStyle(node).animationName);check(editMotion==="shell-content-refresh",`${label}: course edit entry has a localized reveal`);await page.locator("#courseEditForm").screenshot({path:path.join(evidence,`${label}-edit-mid.png`)});await page.locator("#cancelCourseEdit").click();const returnMotion=await page.locator("#courseDetailView").evaluate(node=>getComputedStyle(node).animationName);check(returnMotion==="shell-content-refresh",`${label}: course edit return has a localized reveal`);await page.locator("#closeDialog").click();await page.locator("#courseDialog[data-closing='true']").waitFor();check(await page.locator("#courseDialog").evaluate(node=>node.open),`${label}: close remains open during canonical exit`);await page.waitForFunction(()=>!document.querySelector("#courseDialog").open);
      }
      check(errors.length===0,`${label}: no runtime errors ${JSON.stringify(errors)}`);matrix.push({label,touch,mouse,keyboard,low,high,methodMotion});await context.close();
    }
    const reduced=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,colorScheme:"dark",reducedMotion:"reduce"});const page=await reduced.newPage();await page.goto(`${base}/`);const reducedWelcome=await welcomeState(page);check(reducedWelcome.animation==="none",`reduced motion removes Welcome repetition ${JSON.stringify(reducedWelcome)}`);await page.evaluate(()=>localStorage.setItem("anyclass.onboardingCompleted","1"));await seed(page);await page.goto(`${base}/timetable/`);await page.locator("#app:not([hidden])").waitFor();await page.locator("#next").click();const reducedWeek=await page.locator("#mobileWeekList").evaluate(node=>getComputedStyle(node).animationName);check(reducedWeek==="none","reduced motion keeps week replacement immediate and usable");await page.locator(".mobile-course").first().click();await page.locator("#courseDialog[open]").waitFor();await page.locator("#closeDialog").click();check(await page.locator("#courseDialog").evaluate(node=>!node.open),"reduced motion closes the sheet immediately");await page.screenshot({path:path.join(evidence,"reduced-motion-final.png")});await reduced.close();
    fs.writeFileSync(path.join(evidence,"measurements.json"),JSON.stringify({result:"ISSUE030_MOTION_COVERAGE_PASS",assertions,matrix,reducedWelcome},null,2));console.log(JSON.stringify({result:"ISSUE030_MOTION_COVERAGE_PASS",assertions,cases:matrix.length,evidence},null,2));
  }finally{await browser.close();if(server.listening)server.close()}
})().catch(error=>{console.error(error);if(server.listening)server.close();process.exitCode=1});
