"use strict";

const assert=require("node:assert/strict");
const fs=require("node:fs");
const http=require("node:http");
const path=require("node:path");
const {chromium}=require("playwright");
const {evidenceDirectory}=require("./local-artifacts");

const root=path.resolve(__dirname,"../app");
const externalBase=process.env.ANYCLASS_TEST_BASE?.replace(/\/$/,"")||"";
const evidence=evidenceDirectory(externalBase?"issue028-final-ui-motion-beta":"issue028-final-ui-motion");
const executablePath=[path.join(process.env.LOCALAPPDATA||"","Google","Chrome","Application","chrome.exe"),path.join(process.env["PROGRAMFILES(X86)"]||"","Microsoft","Edge","Application","msedge.exe")].find(fs.existsSync);
const mime=file=>file.endsWith(".js")?"application/javascript":file.endsWith(".css")?"text/css":file.endsWith(".svg")?"image/svg+xml":file.endsWith(".png")?"image/png":file.endsWith(".json")?"application/json":"text/html";
const server=http.createServer((request,response)=>{let name=decodeURIComponent(new URL(request.url,"http://local").pathname);if(name.endsWith("/"))name+="index.html";const file=path.resolve(root,"."+name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){response.writeHead(404);response.end();return}response.writeHead(200,{"content-type":mime(file),"cache-control":"no-store"});response.end(fs.readFileSync(file))});
const fixture={schemaVersion:1,school:{id:null,name:"Synthetic Layout University With A Long Display Name"},semester:{academicYear:"2026-2027",term:"1"},timetableName:"Synthetic Layout Timetable With A Long Display Name",meetings:[{courseName:"Course Alpha",teacher:"Teacher With A Long Display Name",locationRaw:"Teaching Building A Very Long Room Description 101",weekday:1,startPeriod:1,endPeriod:2,weeks:[1,2,3,4],isAdjusted:false},{courseName:"Course Beta",teacher:"Teacher B",locationRaw:"Room B",weekday:3,startPeriod:3,endPeriod:4,weeks:[1,2,3,4],isAdjusted:true}]};

(async()=>{
  fs.mkdirSync(evidence,{recursive:true});
  if(!externalBase)await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
  const base=externalBase||`http://127.0.0.1:${server.address().port}`;
  const browser=await chromium.launch({executablePath,headless:true,args:["--disable-background-networking","--disable-features=OverlayScrollbar"]});
  let assertions=0;const check=(value,message)=>{assert(value,message);assertions++};const matrix=[];
  const seed=async page=>{await page.goto(`${base}/import/?method=file`);await page.locator("#fileInput").setInputFiles({name:"issue028.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(fixture))});await page.locator("#filePreview:not([hidden])").waitFor();await page.locator("#fileSemesterStart").fill("2026-08-31");await page.waitForFunction(()=>document.querySelector("#filePreview").dataset.importState==="PREVIEW_READY");await page.locator("#fileSave").click();await page.waitForFunction(()=>document.querySelector("#filePreview").dataset.importState==="SUCCESS")};
  try{
    for(const theme of ["light","dark"])for(const width of [390,430,768,1280]){
      const mobile=width<700,height=mobile?844:900;
      const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,colorScheme:theme});
      const page=await context.newPage(),errors=[];page.on("pageerror",error=>errors.push(String(error)));page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});

      await page.goto(`${base}/`);await page.locator(".welcome-dialog[open] [data-onboarding-primary]").waitFor();await page.waitForTimeout(80);
      const welcome=page.locator("[data-onboarding-primary]");const welcomeState=await welcome.evaluate(node=>{const own=getComputedStyle(node),ring=getComputedStyle(node,"::after"),rect=node.getBoundingClientRect();return{animations:node.getAnimations().filter(item=>item.animationName==="anyclass-welcome-cta-attention").length,ownOpacity:own.opacity,ownTransform:own.transform,ownOutlineOffset:own.outlineOffset,iterationCount:own.animationIterationCount,ringBorder:ring.borderTopWidth,ringContent:ring.content,ringAnimation:ring.animationName,overflow:document.documentElement.scrollWidth>innerWidth+1,rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height}}});
      check(welcomeState.animations===1&&welcomeState.iterationCount==="3"&&welcomeState.ringBorder==="0px"&&welcomeState.ringContent==="none",`${theme} ${width}: Welcome uses finite surface emphasis without an external frame`);check(welcomeState.ownOpacity==="1"&&welcomeState.ownTransform==="none",`${theme} ${width}: Welcome body stays stable while keyboard focus remains a separate state`);check(!welcomeState.overflow,`${theme} ${width}: Welcome no overflow`);
      const animation=welcome.evaluate(node=>node.getAnimations().find(item=>item.animationName==="anyclass-welcome-cta-attention").currentTime=0);await animation;if(width===390)await page.screenshot({path:path.join(evidence,`${theme}-welcome-low.png`)});await welcome.evaluate(node=>node.getAnimations().find(item=>item.animationName==="anyclass-welcome-cta-attention").currentTime=950);if(width===390)await page.screenshot({path:path.join(evidence,`${theme}-welcome-high.png`)});

      await context.addInitScript(()=>localStorage.setItem("anyclass.onboardingCompleted","1"));await seed(page);
      await page.goto(`${base}/local-status/`);await page.locator("#data:not([hidden])").waitFor();await page.locator("#editTimetableInfo").evaluate(node=>node.scrollIntoView({block:"center"}));
      if(width===390)await page.screenshot({path:path.join(evidence,`${theme}-local-collapsed.png`)});
      const collapsed=await page.locator("#timetableInfoEditor").evaluate(node=>({height:node.getBoundingClientRect().height,hidden:node.getAttribute("aria-hidden"),inert:node.inert}));check(collapsed.height<1&&collapsed.hidden==="true"&&collapsed.inert,`${theme} ${width}: Local Data starts collapsed and inert`);
      await page.locator("#editTimetableInfo").click();await page.waitForTimeout(90);const mid=await page.locator("#timetableInfoEditor").evaluate(node=>({height:node.getBoundingClientRect().height,open:node.dataset.open,transition:getComputedStyle(node).transitionProperty}));if(width===390)await page.screenshot({path:path.join(evidence,`${theme}-local-mid.png`)});await page.waitForTimeout(220);if(width===390)await page.screenshot({path:path.join(evidence,`${theme}-local-expanded.png`)});const expanded=await page.locator("#timetableInfoEditor").evaluate(node=>node.getBoundingClientRect().height);check(mid.open==="true"&&mid.height>0&&mid.height<expanded&&mid.transition.includes("grid-template-rows"),`${theme} ${width}: Local Data has a real intermediate disclosure frame ${JSON.stringify({mid,expanded})}`);
      const actions=await page.locator("#timetableInfoForm .actions").evaluate(node=>{const buttons=[...node.querySelectorAll("button")].map(item=>{const rect=item.getBoundingClientRect();return{x:rect.x,width:rect.width,height:rect.height,background:getComputedStyle(item).backgroundColor}});return{buttons,gap:buttons[1].x-(buttons[0].x+buttons[0].width)}});check(actions.buttons.every(item=>item.height>=44)&&actions.gap>=12&&actions.buttons[0].background!==actions.buttons[1].background,`${theme} ${width}: Local Data actions keep touch size, separation, and hierarchy`);if(width===390)await page.locator("#timetableInfoForm .actions").screenshot({path:path.join(evidence,`${theme}-local-actions.png`)});await page.locator("#cancelTimetableInfo").click();await page.waitForTimeout(260);check(await page.locator("#timetableInfoEditor").evaluate(node=>node.getBoundingClientRect().height<1&&node.inert),`${theme} ${width}: Local Data reverse disclosure completes`);

      await page.goto(`${base}/today/`);await page.locator("#app:not([hidden])").waitFor();await page.evaluate(()=>AnyClassHolidayReminders.render(new Date(2026,9,5)));await page.locator("[data-holiday-reminder]:not([hidden])").waitFor();const holidayGap=await page.evaluate(()=>{const selector=document.querySelector("[data-timetable-switcher]").getBoundingClientRect(),notice=document.querySelector("[data-holiday-reminder]").getBoundingClientRect();return{gap:notice.top-selector.bottom,overflow:document.documentElement.scrollWidth>innerWidth+1}});check(holidayGap.gap>=10&&holidayGap.gap<=26&&!holidayGap.overflow,`${theme} ${width}: Today holiday spacing follows normal rhythm ${JSON.stringify(holidayGap)}`);if(width===390)await page.screenshot({path:path.join(evidence,`${theme}-today-holiday.png`)});await page.evaluate(async()=>{await AnyClassHolidayReminders.render(new Date(2026,9,8));scrollTo(0,0)});check(await page.locator("[data-holiday-reminder]").isHidden(),`${theme} ${width}: Today non-holiday path hides notice`);if(width===390)await page.screenshot({path:path.join(evidence,`${theme}-today-no-holiday.png`)});

      await page.goto(`${base}/timetable/`);await page.locator("#app:not([hidden])").waitFor();const card=page.locator(mobile?".mobile-course":".course-card").first();await card.click();await page.locator("#courseDialog[open]").waitFor();await page.waitForTimeout(300);
      const states=[{name:"short-no-badge",title:"Course A",badge:false},{name:"short-badge",title:"Course A",badge:true},{name:"long-no-badge",title:"毛泽东思想和中国特色社会主义理论体系概论",badge:false},{name:"long-badge",title:"毛泽东思想和中国特色社会主义理论体系概论",badge:true}];
      const sheet=[];for(const state of states){await page.evaluate(value=>{document.querySelector("#dialogTitle").textContent=value.title;document.querySelector("#dialogStatusRow").hidden=!value.badge;document.querySelector("#dialogAdjusted").hidden=!value.badge},state);await page.waitForTimeout(30);const geometry=await page.evaluate(()=>{const sheet=document.querySelector("#courseDialog .dialog-body").getBoundingClientRect(),handle=document.querySelector("#courseDialog .sheet-grabber").getBoundingClientRect(),heading=document.querySelector("#courseDialog .dialog-heading").getBoundingClientRect(),title=document.querySelector("#dialogTitle").getBoundingClientRect(),close=document.querySelector("#closeDialog").getBoundingClientRect(),status=document.querySelector("#dialogStatusRow").hidden?null:document.querySelector("#dialogStatusRow").getBoundingClientRect();return{sheet,handle,heading,title,close,status,overflow:document.documentElement.scrollWidth>innerWidth+1}});check(!geometry.overflow&&geometry.title.right<=geometry.close.left-8&&geometry.title.left>=geometry.sheet.left-1,`${theme} ${width} ${state.name}: title stays out of close safe area`);if(mobile){check(geometry.handle.top-geometry.sheet.top<=14&&geometry.handle.bottom<=geometry.title.top,`${theme} ${width} ${state.name}: grabber owns a top handle zone`);if(state.badge)check(geometry.status.bottom<=geometry.title.top-4,`${theme} ${width} ${state.name}: badge owns a separate row`)}if((width===390||width===430)&&theme==="light")await page.screenshot({path:path.join(evidence,`course-${width}-${state.name}.png`)});sheet.push({state:state.name,...geometry})}
      check(errors.length===0,`${theme} ${width}: no runtime errors ${JSON.stringify(errors)}`);matrix.push({theme,width,welcomeState,collapsed,mid,expanded,actions,holidayGap,sheet});await context.close();
    }

    const reduced=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:"reduce"});const reducedPage=await reduced.newPage();await reducedPage.goto(`${base}/`);await reducedPage.locator(".welcome-dialog[open] [data-onboarding-primary]").waitFor();const reducedWelcome=await reducedPage.locator("[data-onboarding-primary]").evaluate(node=>{const own=getComputedStyle(node),ring=getComputedStyle(node,"::after");return{animation:own.animationName,border:ring.borderTopWidth,content:ring.content,opacity:own.opacity}});check(reducedWelcome.animation==="none"&&reducedWelcome.border==="0px"&&reducedWelcome.content==="none"&&reducedWelcome.opacity==="1",`reduced motion keeps a static primary button without an external frame ${JSON.stringify(reducedWelcome)}`);await reduced.addInitScript(()=>localStorage.setItem("anyclass.onboardingCompleted","1"));await seed(reducedPage);await reducedPage.goto(`${base}/local-status/`);await reducedPage.locator("#data:not([hidden])").waitFor();await reducedPage.locator("#editTimetableInfo").click();const reducedDisclosure=await reducedPage.locator("#timetableInfoEditor").evaluate(node=>({transition:getComputedStyle(node).transitionDuration,height:node.getBoundingClientRect().height}));check(reducedDisclosure.transition.split(",").every(value=>parseFloat(value)===0)&&reducedDisclosure.height>0,"reduced motion disables disclosure travel without hiding controls");await reduced.close();
    const landscape=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,colorScheme:"light"});const landscapePage=await landscape.newPage();await landscapePage.goto(`${base}/`);await landscapePage.locator(".welcome-dialog[open]").waitFor();check(!await landscapePage.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),"landscape Welcome has no horizontal overflow");await landscape.addInitScript(()=>localStorage.setItem("anyclass.onboardingCompleted","1"));await seed(landscapePage);await landscapePage.goto(`${base}/local-status/`);await landscapePage.locator("#data:not([hidden])").waitFor();await landscapePage.locator("#editTimetableInfo").click();await landscapePage.waitForTimeout(240);check(!await landscapePage.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),"landscape Local Data editor has no horizontal overflow");await landscapePage.locator("#cancelTimetableInfo").click();await landscapePage.locator("#editTimetableInfo").click();await landscapePage.locator("#cancelTimetableInfo").click();await landscapePage.waitForTimeout(240);check(await landscapePage.locator("#timetableInfoEditor").evaluate(node=>node.inert&&node.getBoundingClientRect().height<1),"rapid disclosure reverse leaves one collapsed inert editor");await landscapePage.goto(`${base}/timetable/`);await landscapePage.locator("#app:not([hidden])").waitFor();await landscapePage.locator(".course-card").first().click();await landscapePage.locator("#courseDialog[open]").waitFor();await landscapePage.evaluate(()=>{document.querySelector("#dialogTitle").textContent="毛泽东思想和中国特色社会主义理论体系概论";document.querySelector("#dialogStatusRow").hidden=false;document.querySelector("#dialogAdjusted").hidden=false});const landscapeHeader=await landscapePage.evaluate(()=>{const title=document.querySelector("#dialogTitle").getBoundingClientRect(),close=document.querySelector("#closeDialog").getBoundingClientRect();return{overflow:document.documentElement.scrollWidth>innerWidth+1,titleRight:title.right,closeLeft:close.left}});check(!landscapeHeader.overflow&&landscapeHeader.titleRight<=landscapeHeader.closeLeft-8,`landscape long title keeps close safe area ${JSON.stringify(landscapeHeader)}`);await landscapePage.screenshot({path:path.join(evidence,"landscape-course-long-badge.png")});await landscape.close();
    fs.writeFileSync(path.join(evidence,"measurements.json"),JSON.stringify({result:"ISSUE028_FINAL_UI_MOTION_PASS",assertions,matrix,reducedWelcome},null,2));console.log(JSON.stringify({result:"ISSUE028_FINAL_UI_MOTION_PASS",assertions,cases:matrix.length,evidence},null,2));
  }finally{await browser.close();if(server.listening)server.close()}
})().catch(error=>{console.error(error);if(server.listening)server.close();process.exitCode=1});
