"use strict";

const assert=require("node:assert/strict");
const fs=require("node:fs");
const http=require("node:http");
const path=require("node:path");
const zlib=require("node:zlib");
const {chromium}=require("playwright");
const {evidenceDirectory}=require("./local-artifacts");
const root=path.resolve(__dirname,"../app"),evidence=evidenceDirectory("issue027-import-continuity");
const externalBase=String(process.env.ANYCLASS_TEST_BASE||"").replace(/\/$/,"");
const server=http.createServer((request,response)=>{let name=decodeURIComponent(new URL(request.url,"http://local").pathname);if(name.endsWith("/"))name+="index.html";const file=path.resolve(root,"."+name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){response.writeHead(404);response.end();return}response.writeHead(200,{"content-type":file.endsWith(".js")?"application/javascript":file.endsWith(".css")?"text/css":"text/html","cache-control":"no-store"});response.end(fs.readFileSync(file))});
const fixture={schemaVersion:1,school:{id:null,name:"Synthetic University"},semester:{academicYear:"2026-2027",term:"1"},timetableName:"Continuity Test",meetings:[{courseName:"Course Alpha",teacher:"Teacher A",locationRaw:"Room A",weekday:1,startPeriod:1,endPeriod:2,weeks:[1,2,3]},{courseName:"Course Beta",teacher:"Teacher B",locationRaw:"Room B",weekday:3,startPeriod:3,endPeriod:4,weeks:[1,2,3]}]};
const decodePng=buffer=>{let offset=8,width=0,height=0,depth=0,color=0,idat=[];while(offset<buffer.length){const length=buffer.readUInt32BE(offset),type=buffer.toString("ascii",offset+4,offset+8),data=buffer.subarray(offset+8,offset+8+length);offset+=12+length;if(type==="IHDR"){width=data.readUInt32BE(0);height=data.readUInt32BE(4);depth=data[8];color=data[9]}else if(type==="IDAT")idat.push(data);else if(type==="IEND")break}assert.equal(depth,8);assert([2,6].includes(color));const channels=color===6?4:3,raw=zlib.inflateSync(Buffer.concat(idat)),stride=width*channels,pixels=Buffer.alloc(stride*height);let source=0;for(let y=0;y<height;y++){const filter=raw[source++],row=y*stride,prior=row-stride;for(let x=0;x<stride;x++){const value=raw[source++],left=x>=channels?pixels[row+x-channels]:0,up=y?pixels[prior+x]:0,upLeft=y&&x>=channels?pixels[prior+x-channels]:0;pixels[row+x]=(value+(filter===1?left:filter===2?up:filter===3?Math.floor((left+up)/2):filter===4?(()=>{const p=left+up-upLeft,pa=Math.abs(p-left),pb=Math.abs(p-up),pc=Math.abs(p-upLeft);return pa<=pb&&pa<=pc?left:pb<=pc?up:upLeft})():0))&255}}return{width,height,channels,pixels}};
const renderedDifference=(left,right)=>{const a=decodePng(left),b=decodePng(right);assert.equal(a.width,b.width);assert.equal(a.height,b.height);assert.equal(a.channels,b.channels);let changed=0,totalDelta=0;for(let index=0;index<a.pixels.length;index+=a.channels){let delta=0;for(let channel=0;channel<3;channel++)delta+=Math.abs(a.pixels[index+channel]-b.pixels[index+channel]);if(delta>9)changed++;totalDelta+=delta}return{changedRatio:changed/(a.width*a.height),meanChannelDelta:totalDelta/(a.width*a.height*3)}};

(async()=>{
  if(!externalBase)await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const base=externalBase||`http://127.0.0.1:${server.address().port}`;
  const executablePath=[path.join(process.env.LOCALAPPDATA||"","Google","Chrome","Application","chrome.exe"),path.join(process.env["PROGRAMFILES(X86)"]||"","Microsoft","Edge","Application","msedge.exe")].find(fs.existsSync);
  const browser=await chromium.launch({executablePath,headless:true});let assertions=0;const check=(value,message)=>{assert(value,message);assertions++};const matrix=[];
  try{
    for(const theme of ["light","dark"])for(const width of [390,430]){
      const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true,colorScheme:theme});await context.addInitScript(()=>localStorage.setItem("anyclass.onboardingCompleted","1"));const page=await context.newPage(),errors=[];page.on("pageerror",error=>errors.push(String(error)));page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});
      await page.goto(`${base}/import/?method=file`);await page.evaluate(()=>{document.querySelector("#shared-file-preview").style.marginTop="760px";document.querySelector("#fileSubmitMessage").style.marginTop="900px";window.__issue027={scrolls:[],statusStarts:0,countdown:[],todayRequests:0};const original=window.scrollTo.bind(window);window.scrollTo=options=>{window.__issue027.scrolls.push({options,previewHidden:document.querySelector("#filePreview").hidden,state:document.querySelector("#filePreview").dataset.importState,statusConnected:document.querySelector("#fileSubmitMessage").isConnected});return original(options)};document.querySelector("#fileSubmitMessage").addEventListener("animationstart",()=>window.__issue027.statusStarts++);new MutationObserver(()=>{const value=document.querySelector("[data-import-countdown]")?.textContent;if(value&&!window.__issue027.countdown.includes(value))window.__issue027.countdown.push(value)}).observe(document.querySelector("#fileSubmitMessage"),{childList:true,characterData:true,subtree:true})});
      await page.screenshot({path:path.join(evidence,`${theme}-${width}-file-before.png`),fullPage:false});
      await page.locator("#fileInput").setInputFiles({name:"synthetic.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(fixture))});await page.locator("#filePreview:not([hidden])").waitFor();await page.waitForTimeout(60);await page.screenshot({path:path.join(evidence,`${theme}-${width}-preview-mid.png`),fullPage:false});await page.waitForTimeout(500);await page.screenshot({path:path.join(evidence,`${theme}-${width}-preview-destination.png`),fullPage:false});
      const previewState=await page.evaluate(()=>({scrolls:window.__issue027.scrolls.slice(),top:document.querySelector("#filePreview").getBoundingClientRect().top,behavior:getComputedStyle(document.documentElement).scrollBehavior,visible:!document.querySelector("#filePreview").hidden}));
      check(previewState.visible&&previewState.scrolls.some(item=>item.options?.behavior==="smooth"&&!item.previewHidden),`${theme} ${width}: preview scroll occurs after preview exists`);check(previewState.top>=0&&previewState.top<250,`${theme} ${width}: preview header lands comfortably`);check(previewState.behavior==="smooth",`${theme} ${width}: existing shell scroll behavior remains unchanged`);
      await page.locator("#fileSemesterStart").fill("2026-08-31");await page.waitForFunction(()=>document.querySelector("#filePreview").dataset.importState==="PREVIEW_READY");await page.evaluate(()=>{window.__issue027.scrolls=[];window.scrollTo({top:0,behavior:"auto"});document.querySelector("#fileSave").click()});await page.waitForFunction(()=>document.querySelector("#filePreview").dataset.importState==="SUCCESS");await page.waitForTimeout(600);await page.screenshot({path:path.join(evidence,`${theme}-${width}-success-3.png`),fullPage:false});
      const actions=page.locator("#filePreview .file-preview-actions"),successArea=page.locator("#fileSubmitMessage"),countdown=page.locator("[data-import-countdown]");const stableShots=[await successArea.screenshot({mask:[countdown]})];
      const successInitial=await page.evaluate(()=>{const node=document.querySelector("#fileSubmitMessage"),actions=node.closest(".file-preview-actions"),card=document.querySelector("#filePreview");return{starts:window.__issue027.statusStarts,text:node.innerText,scrolls:window.__issue027.scrolls.slice(),border:getComputedStyle(actions).borderTopWidth,cardBorder:getComputedStyle(card).borderTopWidth,opacity:getComputedStyle(node).opacity,animation:getComputedStyle(node).animationName}});
      check(successInitial.text.includes("3 秒"),`${theme} ${width}: stable result starts at 3 seconds ${JSON.stringify(successInitial)}`);check(successInitial.scrolls.some(item=>item.options?.behavior==="smooth"&&item.state==="SUCCESS"),`${theme} ${width}: result renders before targeted scroll ${JSON.stringify(successInitial.scrolls)}`);check(successInitial.border==="0px"&&parseFloat(successInitial.cardBorder)>0,`${theme} ${width}: internal divider removed and outer card retained`);
      await page.waitForFunction(()=>document.querySelector("[data-import-countdown]")?.textContent==="2");await page.waitForTimeout(50);await page.screenshot({path:path.join(evidence,`${theme}-${width}-success-2.png`),fullPage:false});stableShots.push(await successArea.screenshot({mask:[countdown]}));const tick2=await page.evaluate(()=>({starts:window.__issue027.statusStarts,scrolls:window.__issue027.scrolls.length,opacity:getComputedStyle(document.querySelector("#fileSubmitMessage")).opacity,animation:getComputedStyle(document.querySelector("#fileSubmitMessage")).animationName}));
      await page.waitForFunction(()=>document.querySelector("[data-import-countdown]")?.textContent==="1");await page.waitForTimeout(50);await page.screenshot({path:path.join(evidence,`${theme}-${width}-success-1.png`),fullPage:false});stableShots.push(await successArea.screenshot({mask:[countdown]}));const tick1=await page.evaluate(()=>({starts:window.__issue027.statusStarts,scrolls:window.__issue027.scrolls.length,sequence:window.__issue027.countdown.slice(),sameNode:document.querySelector("#fileSubmitMessage").dataset.importSuccess==="true",opacity:getComputedStyle(document.querySelector("#fileSubmitMessage")).opacity,animation:getComputedStyle(document.querySelector("#fileSubmitMessage")).animationName}));
      const pixelDiffs=[renderedDifference(stableShots[0],stableShots[1]),renderedDifference(stableShots[1],stableShots[2])];check(tick2.starts===successInitial.starts&&tick1.starts===successInitial.starts,`${theme} ${width}: countdown does not restart status animation`);check(tick2.scrolls===tick1.scrolls&&tick1.sequence.join(",")==="3,2,1",`${theme} ${width}: countdown updates only its value without repeated scrolling`);check(tick1.sameNode&&tick2.opacity==="1"&&tick1.opacity==="1",`${theme} ${width}: success parent remains stable through ticks`);check(pixelDiffs.every(item=>item.changedRatio<.002&&item.meanChannelDelta<.05),`${theme} ${width}: masked success card pixels remain stable through 3/2/1 ${JSON.stringify(pixelDiffs)}`);check(errors.length===0,`${theme} ${width}: runtime errors zero ${JSON.stringify(errors)}`);matrix.push({theme,width,previewState,successInitial,tick2,tick1,pixelDiffs});await context.close();
    }
    for(const reduced of [false,true]){
      const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:reduced?"reduce":"no-preference"});await context.addInitScript(()=>localStorage.setItem("anyclass.onboardingCompleted","1"));const page=await context.newPage();await page.goto(`${base}/import/?method=file`);await page.evaluate(()=>{document.querySelector("#shared-file-preview").style.marginTop="760px";window.__scrolls=[];const original=window.scrollTo.bind(window);window.scrollTo=options=>{window.__scrolls.push(options);return original(options)}});await page.locator("#fileInput").setInputFiles({name:"synthetic.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(fixture))});await page.locator("#filePreview:not([hidden])").waitFor();await page.waitForTimeout(100);const behavior=await page.evaluate(()=>window.__scrolls.at(-1)?.behavior);check(behavior===(reduced?"auto":"smooth"),`targeted preview navigation respects reduced-motion=${reduced}`);await context.close();
    }
    for(const theme of ["light","dark"]){
      const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,colorScheme:theme});const page=await context.newPage();await page.goto(`${base}/`);await page.locator(".welcome-dialog[open] [data-onboarding-primary]").waitFor();await page.waitForTimeout(500);const button=page.locator("[data-onboarding-primary]");const styles=await button.evaluate(node=>{const own=getComputedStyle(node),halo=getComputedStyle(node,"::after"),rect=node.getBoundingClientRect(),dialog=node.closest("dialog");return{ownOpacity:own.opacity,ownTransform:own.transform,ownBorder:own.borderTopWidth,ownOutlineStyle:own.outlineStyle,active:document.activeElement===node,dialogActive:document.activeElement===dialog,iterationCount:own.animationIterationCount,haloBorder:halo.borderTopWidth,haloContent:halo.content,animation:own.animationName,rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height}}});check(styles.haloBorder==="0px"&&styles.haloContent==="none",`${theme}: Welcome has no external blue frame`);check(styles.dialogActive&&!styles.active&&styles.ownOutlineStyle==="none",`${theme}: initial programmatic focus stays on the dialog, not the CTA`);check(styles.ownOpacity==="1"&&styles.ownTransform==="none"&&styles.animation==="anyclass-welcome-cta-attention"&&styles.iterationCount==="3",`${theme}: Welcome body uses finite surface emphasis`);await button.evaluate(node=>node.getAnimations().find(animation=>animation.animationName==="anyclass-welcome-cta-attention").currentTime=0);await page.screenshot({path:path.join(evidence,`${theme}-welcome-low.png`),fullPage:false});await button.evaluate(node=>node.getAnimations().find(animation=>animation.animationName==="anyclass-welcome-cta-attention").currentTime=950);await page.screenshot({path:path.join(evidence,`${theme}-welcome-high.png`),fullPage:false});const after=await button.boundingBox();check(Math.abs(after.width-styles.rect.width)<1.25&&Math.abs(after.height-styles.rect.height)<1.25,`${theme}: surface pulse leaves hit geometry fixed ${JSON.stringify({before:styles.rect,after})}`);await context.close();
    }
    const auto=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await auto.addInitScript(()=>localStorage.setItem("anyclass.onboardingCompleted","1"));const page=await auto.newPage();let todayNavigations=0;page.on("framenavigated",frame=>{if(frame===page.mainFrame()&&new URL(frame.url()).pathname==="/today/")todayNavigations++});await page.goto(`${base}/import/?method=file`);await page.locator("#fileInput").setInputFiles({name:"synthetic.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(fixture))});await page.locator("#fileSemesterStart").fill("2026-08-31");await page.waitForFunction(()=>document.querySelector("#filePreview").dataset.importState==="PREVIEW_READY");await page.evaluate(()=>document.querySelector("#fileSave").click());await page.waitForURL(`${base}/today/`,{timeout:7000});await page.waitForTimeout(400);check(todayNavigations===1,"automatic Today navigation fires once");await auto.close();
    const immediate=await browser.newContext({viewport:{width:430,height:844},isMobile:true,hasTouch:true});await immediate.addInitScript(()=>localStorage.setItem("anyclass.onboardingCompleted","1"));const immediatePage=await immediate.newPage();let immediateNavigations=0;immediatePage.on("framenavigated",frame=>{if(frame===immediatePage.mainFrame()&&new URL(frame.url()).pathname==="/today/")immediateNavigations++});await immediatePage.goto(`${base}/import/?method=file`);await immediatePage.locator("#fileInput").setInputFiles({name:"synthetic.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify({...fixture,timetableName:"Immediate Navigation Test"}))});await immediatePage.locator("#fileSemesterStart").fill("2026-08-31");await immediatePage.waitForFunction(()=>document.querySelector("#filePreview").dataset.importState==="PREVIEW_READY");await immediatePage.evaluate(()=>document.querySelector("#fileSave").click());await immediatePage.waitForFunction(()=>document.querySelector("#filePreview").dataset.importState==="SUCCESS");await immediatePage.evaluate(()=>{document.querySelector("#fileGoToday").click();document.querySelector("#fileGoToday").click()});await immediatePage.waitForURL(`${base}/today/`,{timeout:3000});await immediatePage.waitForTimeout(300);check(immediateNavigations===1,"immediate Today action fires once even on repeated activation");await immediate.close();
    fs.writeFileSync(path.join(evidence,"measurements.json"),JSON.stringify({result:"ISSUE027_IMPORT_CONTINUITY_PASS",assertions,matrix},null,2));console.log(JSON.stringify({result:"ISSUE027_IMPORT_CONTINUITY_PASS",assertions,evidence},null,2));
  }finally{await browser.close();if(!externalBase)server.close()}
})().catch(error=>{console.error(error);if(!externalBase)server.close();process.exitCode=1});
