"use strict";
const assert=require("node:assert/strict"),http=require("node:http"),fs=require("node:fs"),path=require("node:path");
const {chromium}=require("playwright"),app=path.resolve(__dirname,"../app");
const html=`<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="/assets/timetable/product-shell.css"></head><body><main><button id="opener">Open</button><div id="first">First</div><div id="second">Second</div><dialog id="sheet"><div class="dialog-body"><button id="inside">Inside</button></div></dialog></main><script src="/assets/timetable/product-shell.js"></script></body></html>`;
const server=http.createServer((req,res)=>{let pathname=decodeURIComponent(new URL(req.url,"http://local").pathname);if(pathname==="/__motion/"){res.writeHead(200,{"content-type":"text/html"});res.end(html);return}const file=path.resolve(app,"."+pathname);if(!file.startsWith(app+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return}res.writeHead(200,{"content-type":file.endsWith(".js")?"application/javascript":file.endsWith(".css")?"text/css":"text/html"});res.end(fs.readFileSync(file))});
(async()=>{await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const executablePath=[path.join(process.env.LOCALAPPDATA||"","Google","Chrome","Application","chrome.exe"),path.join(process.env["PROGRAMFILES(X86)"]||"","Microsoft","Edge","Application","msedge.exe")].find(fs.existsSync);const browser=await chromium.launch({executablePath,headless:true,args:["--disable-background-networking"]});let assertions=0;const check=(value,label)=>{assert(value,label);assertions++};try{const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();await page.goto(`http://127.0.0.1:${server.address().port}/__motion/`);const tokens=await page.evaluate(()=>{const style=getComputedStyle(document.documentElement);return ["--motion-feedback","--motion-transition","--motion-enter","--motion-exit","--motion-deliberate"].map(name=>style.getPropertyValue(name).trim())});check(JSON.stringify(tokens)===JSON.stringify(["160ms","240ms","240ms","160ms","360ms"]),"semantic motion tokens");
  const dialog=await page.evaluate(async()=>{const sheet=document.querySelector("#sheet"),opener=document.querySelector("#opener"),inside=document.querySelector("#inside");opener.focus();AnyClassMotion.openDialog(sheet,{focus:inside});const first=AnyClassMotion.closeDialog(sheet),second=AnyClassMotion.closeDialog(sheet);const idempotent=first===second;sheet.querySelector(".dialog-body").dispatchEvent(new AnimationEvent("animationend",{animationName:"shell-sheet-exit",bubbles:true}));await first;const closed=!sheet.open&&document.activeElement===opener;AnyClassMotion.openDialog(sheet,{focus:inside});const interrupted=AnyClassMotion.closeDialog(sheet);AnyClassMotion.openDialog(sheet,{focus:inside});await interrupted;await new Promise(resolve=>setTimeout(resolve,360));const reopenSafe=sheet.open&&!sheet.hasAttribute("data-closing");await AnyClassMotion.closeDialog(sheet,{timeout:30});return{idempotent,closed,reopenSafe,timeoutClosed:!sheet.open}});check(dialog.idempotent,"repeated close is idempotent");check(dialog.closed,"close restores focus");check(dialog.reopenSafe,"reopen cancels stale close");check(dialog.timeoutClosed,"missing animation event has timeout fallback");
  const navigation=await page.evaluate(async()=>{const calls=[];window.scrollTo=options=>calls.push(options);const first=AnyClassMotion.navigate(document.querySelector("#first")),second=AnyClassMotion.navigate(document.querySelector("#second"));const result=await Promise.all([first,second]);return{result,calls,active:document.activeElement.id}});check(navigation.result[0]===false&&navigation.result[1]===true,"new navigation supersedes old request");check(navigation.calls.length===1&&navigation.active==="second","semantic navigation lands once on latest target");
  await page.emulateMedia({reducedMotion:"reduce"});await page.waitForFunction(()=>document.documentElement.dataset.reducedMotion==="reduce");const reduced=await page.evaluate(async()=>{const sheet=document.querySelector("#sheet");AnyClassMotion.openDialog(sheet);await AnyClassMotion.closeDialog(sheet);return{closed:!sheet.open,mode:AnyClassMotion.prefersReducedMotion(),animation:getComputedStyle(document.querySelector(".refresh-button.is-refreshing span")||document.body).animationName}});check(reduced.closed&&reduced.mode,"runtime reduced-motion change closes immediately");await context.close();console.log(JSON.stringify({result:"MOTION_REFINEMENT_BROWSER_PASS",assertions},null,2))}finally{await browser.close();server.close()}})().catch(error=>{console.error(error);server.close();process.exitCode=1});
