"use strict";
const assert = require("node:assert/strict");
const http = require("node:http"), fs = require("node:fs"), path = require("node:path"), os = require("node:os");
const {chromium} = require("playwright");
const site = path.resolve(__dirname, "../app");
const evidence = require("./local-artifacts").evidenceDirectory("timetable-consistency");
const server = http.createServer((req, res) => {
  let pathname = decodeURIComponent(new URL(req.url, "http://local").pathname);
  if (pathname.endsWith("/")) pathname += "index.html";
  const file = path.resolve(site, "." + pathname);
  if (!file.startsWith(site) || !fs.existsSync(file)) { res.writeHead(404); res.end("not found"); return; }
  res.writeHead(200, {"content-type": file.endsWith(".js") ? "application/javascript" : file.endsWith(".css") ? "text/css" : "text/html", "cache-control":"no-store"});
  res.end(fs.readFileSync(file));
});
const listen = () => new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
(async () => {
  await listen();
  fs.mkdirSync(evidence,{recursive:true});
  const executablePath = [path.join(process.env.LOCALAPPDATA || "", "Google", "Chrome", "Application", "chrome.exe"), path.join(process.env["PROGRAMFILES(X86)"] || "", "Microsoft", "Edge", "Application", "msedge.exe")].find(fs.existsSync);
  const browser = await chromium.launch({executablePath, headless:true, args:["--disable-background-networking"]});
  const base = process.env.ANYCLASS_BROWSER_BASE?.replace(/\/$/, "") || `http://127.0.0.1:${server.address().port}`;
  const context = await browser.newContext({viewport:{width:390,height:844}});
  const page = await context.newPage();
  page.on("pageerror", error => console.error("PAGE_ERROR", error.message));
  let assertions = 0;
  const check = (value, label) => { assert(value, label); assertions++; };
  try {
    await page.goto(base + "/settings/timetables/");
    await page.waitForSelector("#noTimetables:not([hidden])");
    check(await page.locator("#timetableList article").count() === 0, "initially empty");
    await page.getByRole("button", {name:"新建课表"}).click();
    await page.locator("#timetableName").fill("  First  ");
    await page.locator("#nameForm button[type=submit]").click();
    await page.waitForSelector("#timetableList article");
    check(await page.locator("#timetableList article").count() === 1, "created first");
    const first = await page.evaluate(() => AnyClassTimetableRepository.getActiveTimetable());
    check(first.label === "First", "trimmed label and auto active");
    await page.getByRole("button", {name:"新建课表"}).click();
    await page.locator("#timetableName").fill("Second");
    await page.locator("#nameForm button[type=submit]").click();
    await page.waitForFunction(() => document.querySelectorAll("#timetableList article").length === 2);
    check(await page.locator("#timetableList article").count() === 2, "listed two");
    check((await page.evaluate(() => AnyClassTimetableRepository.getActiveTimetable())).timetableId === first.timetableId, "creation did not steal active");
    const second = (await page.evaluate(() => AnyClassTimetableRepository.listTimetables())).find(row => row.timetableId !== first.timetableId);
    await page.locator("#timetableList article").filter({hasText:"Second"}).getByRole("button", {name:"编辑信息"}).click();
    await page.waitForURL(url => url.pathname === "/local-status/");
    check(await page.locator("#editTimetableName").inputValue() === "Second", "metadata editor prefilled");
    await page.locator("#editTimetableName").fill("Renamed");
    await page.locator("#editSchoolName").fill("  Example University  ");
    await page.locator("#saveTimetableInfo").click();
    await page.waitForFunction(() => document.querySelector("#timetableName")?.textContent === "Renamed");
    const renamed = await page.evaluate(id => AnyClassTimetableRepository.getTimetable(id), second.timetableId);
    check(renamed.label === "Renamed" && renamed.schoolName === "Example University" && renamed.timetableId === second.timetableId, "metadata identity");
    await page.locator("#editTimetableInfo").click();
    await page.locator("#editSchoolName").fill("   ");
    await page.locator("#saveTimetableInfo").click();
    check(await page.locator("#editTimetableError").isVisible(), "empty school rejected");
    await page.locator("#editSchoolName").fill(" Unsaved School ");
    await page.locator("#cancelTimetableInfo").click();
    check((await page.evaluate(id => AnyClassTimetableRepository.getTimetable(id),second.timetableId)).schoolName === "Example University", "cancel discards metadata edit");
    await page.reload();
    await page.waitForSelector("#data:not([hidden])");
    check(await page.locator("#school").innerText() === "Example University", "school metadata survives reload");
    check(!(await page.evaluate(id => AnyClassTimetableRepository.getTimetable(id),first.timetableId)).schoolName, "editing B does not change A school");
    await page.goto(base + "/settings/timetables/");
    await page.locator("#timetableList article").filter({hasText:"Renamed"}).getByRole("button", {name:"切换"}).click();
    await page.waitForFunction(async id => (await AnyClassTimetableRepository.getActiveTimetable())?.timetableId === id, second.timetableId);
    check((await page.evaluate(() => AnyClassTimetableRepository.getActiveTimetable())).timetableId === second.timetableId, "switch active");
    check(await page.locator("#managerStatus").isVisible(), "management switch notice appears");
    await page.locator("#managerStatus").waitFor({state:"hidden",timeout:4500});
    check(true, "management switch notice clears after approximately three seconds");
    await page.reload();
    await page.waitForSelector("#timetableList article");
    check((await page.evaluate(() => AnyClassTimetableRepository.getActiveTimetable())).timetableId === second.timetableId, "active persists reload");
    await page.locator("#timetableList article").filter({hasText:"First"}).getByRole("button", {name:"删除"}).click();
    await page.locator("#deleteDialog [data-close-dialog]").click();
    check((await page.evaluate(() => AnyClassTimetableRepository.listTimetables())).length === 2, "cancel delete preserves data");
    await page.locator("#timetableList article").filter({hasText:"First"}).getByRole("button", {name:"删除"}).click();
    await page.locator("#confirmDelete").click();
    check((await page.evaluate(() => AnyClassTimetableRepository.getActiveTimetable())).timetableId === second.timetableId, "inactive deletion preserves active");
    await page.locator("#timetableList article").getByRole("button", {name:"删除"}).click();
    await page.locator("#confirmDelete").click();
    await page.waitForSelector("#noTimetables:not([hidden])");
    check((await page.evaluate(() => AnyClassTimetableRepository.getActiveTimetable())) === null, "last deletion leaves null active");
    check(await page.evaluate(() => localStorage.getItem("anyclass.onboardingCompleted")) === "1", "onboarding not replayed");
    const importResult = await page.evaluate(async () => {
      const repo = AnyClassTimetableRepository, profile = AnyClassSchoolProfileRegistry.get("school-demo");
      const fixture = term => ({key:`school-demo:2026-2027:${term}`,school:{id:"school-demo",name:"Example University",sourceSystem:"zhengfang-v9"},semester:{academicYear:"2026-2027",term},importedAt:"2026-09-01T00:00:00.000Z",fingerprint:`demo-${term}`,meetings:[{courseName:`Course ${term}`,teacher:"Teacher A",locationRaw:"Building A101",weekday:1,startPeriod:1,endPeriod:2,weeks:Array.from({length:20},(_,i)=>i+1)}]});
      const empty = await repo.createTimetable({label:"Empty active"});
      await AnyClassStorageV2.putLegacyAndMigrate(fixture("1"),profile);
      const firstImported = (await repo.listTimetables()).find(row => row.timetableId !== empty.timetableId).timetableId;
      await AnyClassStorageV2.putLegacyAndMigrate({...fixture("2"),source:"file"},profile);
      const afterDifferentTerm = await repo.listTimetables();
      await AnyClassStorageV2.putLegacyAndMigrate({...fixture("2"),source:"desktop"},profile);
      const afterSameTerm = await repo.listTimetables();
      const stillEmpty = (await repo.getActiveTimetable()).timetableId === empty.timetableId;
      const imported = afterSameTerm.filter(row => row.timetableId !== empty.timetableId);
      const bundles = await Promise.all(imported.map(row => repo.readTimetableBundle(row.timetableId)));
      return {emptyId:empty.timetableId,firstImported,secondImported:imported.find(row=>row.timetableId!==firstImported).timetableId,afterDifferentTerm:afterDifferentTerm.length,afterSameTerm:afterSameTerm.length,stillEmpty,courseCounts:bundles.map(bundle=>bundle.model.courses.length),snapshotCounts:bundles.map(bundle=>bundle.model.snapshots.length)};
    });
    check(importResult.afterDifferentTerm === 3 && importResult.afterSameTerm === 3, "term routing and same-term reimport");
    check(importResult.stillEmpty, "later import does not steal explicit active");
    check(importResult.courseCounts.every(count => count === 1) && importResult.snapshotCounts.every(count => count === 1), "no course or snapshot leakage");
    await page.goto(base + "/local-status/");
    await page.waitForSelector("#data:not([hidden])");
    check(await page.locator("#count").innerText() === "0", "Local Data empty active timetable is not a storage error");
    await page.evaluate(id => AnyClassTimetableRepository.setActiveTimetable(id).then(() => AnyClassShell.dispatchTimetableUpdated({reason:"test-switch"})), importResult.firstImported);
    await page.waitForSelector("#data:not([hidden])");
    check((await page.locator("#timetableName").innerText()).length > 0 && await page.locator("#schemaVersion").innerText() === "4", "Local Data follows active Schema 4 timetable");
    await page.evaluate(id => AnyClassTimetableRepository.setActiveTimetable(id).then(() => AnyClassShell.dispatchTimetableUpdated({reason:"test-switch"})), importResult.emptyId);
    await page.waitForFunction(() => document.querySelector("#count")?.textContent === "0");
    check(await page.locator("#data").isVisible(), "Local Data refreshes after active switch");
    await page.locator("#editTimetableInfo").click();
    await page.evaluate(id => AnyClassTimetableRepository.setActiveTimetable(id).then(() => AnyClassShell.dispatchTimetableUpdated({reason:"test-switch"})), importResult.firstImported);
    await page.waitForFunction(() => document.querySelector("#timetableInfoForm")?.hidden && document.querySelector("#count")?.textContent === "1");
    check(await page.locator("#timetableInfoForm").isHidden(),"active change closes stale metadata editor");
    await page.evaluate(id => AnyClassTimetableRepository.setActiveTimetable(id).then(() => AnyClassShell.dispatchTimetableUpdated({reason:"test-switch"})), importResult.emptyId);
    await page.waitForFunction(() => document.querySelector("#count")?.textContent === "0");
    await page.goto(base + "/today/");
    await page.waitForSelector("[data-timetable-switcher]:not([hidden])");
    check(await page.locator("#activeTimetable").inputValue() === importResult.emptyId, "Today shows empty active");
    check(await page.locator("#emptyState").isVisible(), "Today empty active stays empty");
    await page.locator("#activeTimetable").selectOption(importResult.firstImported);
    await page.waitForSelector("#app:not([hidden])");
    check(await page.locator("[data-switch-status]").getAttribute("class").then(value=>value.includes("is-visible")),"switch notice appears immediately");
    check(await page.locator("#activeTimetable").inputValue() === importResult.firstImported, "Today switched without reload");
    check((await page.locator("#app").innerText()).includes("Course 1"), "populated Today renders own course");
    await page.waitForTimeout(1100);
    await page.locator("#activeTimetable").selectOption(importResult.emptyId);
    await page.waitForSelector("#emptyState:not([hidden])");
    check(await page.locator("#addCourseEmpty").isVisible()&&!await page.locator("#createTimetableEmpty").isVisible(),"selected empty timetable offers Import and Add Course");
    await page.screenshot({path:path.join(evidence,"empty-today-switch-notice-390-light.png"),fullPage:true});
    await page.waitForTimeout(2100);
    check(await page.locator("[data-switch-status]").getAttribute("class").then(value=>value.includes("is-visible")),"new switch restarts notice timer");
    await page.waitForFunction(()=>!document.querySelector("[data-switch-status]")?.classList.contains("is-visible"),null,{timeout:1800});
    await page.locator("[data-switch-status]").waitFor({state:"hidden"});
    check(true,"switch notice clears after approximately three seconds");
    await page.screenshot({path:path.join(evidence,"empty-today-390-light.png"),fullPage:true});
    await page.setViewportSize({width:430,height:844});
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),"empty Today 430 has no horizontal overflow");
    await page.screenshot({path:path.join(evidence,"empty-today-430-light.png"),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    check(await page.locator("#app").isHidden() && !(await page.locator("#heroContent").innerText()).includes("Course 1"), "empty timetable clears stale Today hero");
    check((await page.locator("#emptyState").innerText()).includes("Empty active"), "empty state belongs to selected timetable");
    await page.locator("#activeTimetable").selectOption(importResult.firstImported);
    await page.waitForSelector("#app:not([hidden])");
    check((await page.locator("#app").innerText()).includes("Course 1"), "A data survives A-B-A switching");
    await page.locator("#activeTimetable").selectOption(importResult.secondImported);
    await page.waitForFunction(() => document.querySelector("#app")?.textContent.includes("Course 2") && !document.querySelector("#app")?.hidden);
    check(!(await page.locator("#app").innerText()).includes("Course 1"), "populated B has no A-derived Today content");
    await page.locator("#activeTimetable").selectOption(importResult.firstImported);
    await page.waitForFunction(() => document.querySelector("#app")?.textContent.includes("Course 1") && !document.querySelector("#app")?.hidden);
    check(!(await page.locator("#app").innerText()).includes("Course 2"), "switching B-A restores only A content");
    await page.evaluate(async ids=>{
      const repo=AnyClassTimetableRepository;
      for(const id of [ids.emptyId,ids.firstImported,ids.emptyId]){
        await repo.setActiveTimetable(id);
        AnyClassShell.dispatchTimetableUpdated({reason:"active-timetable"});
      }
    },importResult);
    await page.waitForFunction(() => document.querySelector("#emptyState")?.hidden===false && document.querySelector("#app")?.hidden===true);
    check(!(await page.locator("#heroContent").innerText()).includes("Course 1") && !(await page.locator("#heroContent").innerText()).includes("Course 2"), "rapid A-B-A-empty final state contains no old hero");
    const retained=await page.evaluate(async ids=>Promise.all([ids.firstImported,ids.secondImported].map(async id=>{const bundle=await AnyClassTimetableRepository.readTimetableBundle(id);return {courses:bundle.model.courses.length,snapshots:bundle.model.snapshots.length};})),importResult);
    check(retained.every(row=>row.courses===1&&row.snapshots===1),"switching never deletes source courses or snapshots");
    await page.evaluate(id=>AnyClassTimetableRepository.setActiveTimetable(id).then(()=>AnyClassShell.dispatchTimetableUpdated({reason:"active-timetable"})),importResult.firstImported);
    await page.waitForSelector("#app:not([hidden])");
    await page.goto(base + "/timetable/");
    await page.waitForSelector("#app:not([hidden])");
    check(await page.locator("#activeTimetable").inputValue() === importResult.firstImported, "weekly timetable follows active");
    await page.goto(base + "/export/");
    await page.waitForSelector("#app:not([hidden])");
    check((await page.locator("#activeTimetableName").textContent()).trim().length > 0, "export shows active name");
    await page.goto(base + "/settings/timetables/");
    await page.waitForSelector("#timetableList article");
    await page.locator("#timetableList article").first().getByRole("button", {name:"编辑信息"}).click();
    await page.locator("#editTimetableName").fill("A very long synthetic timetable display name for responsive layout verification");
    await page.locator("#editSchoolName").fill("Example University");
    await page.locator("#saveTimetableInfo").click();
    await page.waitForFunction(() => document.querySelector("#timetableName")?.textContent.includes("A very long synthetic"));
    await page.goto(base + "/settings/timetables/");
    for (const width of [390,430,768,1280]) for (const dark of [false,true]) {
      await page.setViewportSize({width,height:width < 700 ? 844 : 900});
      await page.emulateMedia({colorScheme:dark ? "dark" : "light"});
      await page.goto(base + "/settings/timetables/");
      const geometry = await page.evaluate(() => ({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));
      check(geometry.scroll <= geometry.client, `management overflow ${width} ${dark}`);
      await page.locator("#timetableList article").first().getByRole("button", {name:"删除"}).click();
      const dialog = await page.locator("#deleteDialog").boundingBox();
      check(dialog.x >= 0 && dialog.x + dialog.width <= width + 1, `delete dialog bounds ${width} ${dark}`);
      const dialogGeometry=await page.evaluate(()=>{const box=document.querySelector("#deleteDialog").getBoundingClientRect(),viewport=document.documentElement.clientWidth,left=box.left,right=viewport-box.right,style=getComputedStyle(document.querySelector("#deleteDialog"));return{left,right,width:box.width,viewport,marginLeft:style.marginLeft,marginRight:style.marginRight,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}});
      check(Math.abs(dialogGeometry.left-dialogGeometry.right)<=1&&dialogGeometry.left>=15&&dialogGeometry.overflow<=0,`delete dialog horizontally centered ${width} ${dark}: ${JSON.stringify(dialogGeometry)}`);
      const pointerFocus=await page.evaluate(()=>({active:document.activeElement?.id||document.activeElement?.textContent?.trim(),cancelVisible:document.querySelector("#deleteDialog [data-close-dialog]").matches(":focus-visible"),dialogOutline:getComputedStyle(document.querySelector("#deleteDialog")).outlineStyle}));
      check(pointerFocus.active==="deleteDialog"&&!pointerFocus.cancelVisible&&pointerFocus.dialogOutline==="none",`touch/pointer delete open has no Cancel focus ring ${width} ${dark}`);
      await page.locator("#deleteDialog [data-close-dialog]").click();
      const deleteTrigger=page.locator("#timetableList article").first().getByRole("button", {name:"删除"});
      await deleteTrigger.focus();await deleteTrigger.press("Enter");
      const keyboardFocus=await page.evaluate(()=>({label:document.activeElement?.textContent?.trim(),visible:document.activeElement?.matches(":focus-visible"),outline:getComputedStyle(document.activeElement).outlineStyle}));
      check(keyboardFocus.label==="取消"&&keyboardFocus.visible&&keyboardFocus.outline!=="none",`keyboard delete open keeps visible focus ${width} ${dark}`);
      await page.keyboard.press("Shift+Tab");
      check(await page.evaluate(()=>document.querySelector("#deleteDialog").contains(document.activeElement)||document.activeElement?.id==="deleteDialog"),`delete dialog reverse Tab stays trapped ${width} ${dark}`);
      await page.keyboard.press("Tab");
      check(await page.evaluate(()=>document.querySelector("#deleteDialog").contains(document.activeElement)||document.activeElement?.id==="deleteDialog"),`delete dialog forward Tab stays trapped ${width} ${dark}`);
      await page.locator("#deleteDialog [data-close-dialog]").click();
      if (width === 390 && dark) await page.screenshot({path:path.join(evidence,"anyclass-phase1c-management-mobile-dark.png"),fullPage:true});
      if (width === 1280 && !dark) await page.screenshot({path:path.join(evidence,"anyclass-phase1c-management-desktop-light.png"),fullPage:true});
      await page.goto(base + "/timetable/");
      await page.waitForSelector("[data-timetable-switcher]:not([hidden])");
      const timetable = await page.evaluate(() => ({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,selector:document.querySelector("#activeTimetable").getBoundingClientRect().right}));
      check(timetable.scroll <= timetable.client && timetable.selector <= timetable.client + 1, `timetable/selector bounds ${width} ${dark}`);
      await page.goto(base + "/today/");
      await page.waitForSelector("[data-timetable-switcher]:not([hidden])");
      const today = await page.evaluate(() => ({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,selector:document.querySelector("#activeTimetable").getBoundingClientRect().right}));
      check(today.scroll <= today.client && today.selector <= today.client + 1, `Today/selector bounds ${width} ${dark}`);
      await page.goto(base + "/settings/");
      check(await page.getByRole("link", {name:/课表管理/}).count() === 1, `Settings entry ${width} ${dark}`);
      await page.goto(base + `/local-status/?timetableId=${encodeURIComponent(importResult.firstImported)}&edit=1`);
      await page.waitForSelector("#timetableInfoForm:not([hidden])");
      const metadataLayout=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,form:document.querySelector("#timetableInfoForm").getBoundingClientRect().right,save:document.querySelector("#saveTimetableInfo").getBoundingClientRect().right,saveHeight:document.querySelector("#saveTimetableInfo").getBoundingClientRect().height,cancelHeight:document.querySelector("#cancelTimetableInfo").getBoundingClientRect().height}));
      check(metadataLayout.scroll<=metadataLayout.client && metadataLayout.form<=metadataLayout.client+1 && metadataLayout.save<=metadataLayout.client+1 && metadataLayout.saveHeight>=40 && metadataLayout.cancelHeight>=40,`Local Data metadata layout ${width} ${dark}`);
      await page.locator("#saveTimetableInfo").scrollIntoViewIfNeeded();
      check(await page.locator("#saveTimetableInfo").isVisible() && await page.locator("#cancelTimetableInfo").isVisible(),`Local Data actions reachable ${width} ${dark}`);
      if(width===390||width===430||(!dark&&(width===768||width===1280)))await page.screenshot({path:path.join(evidence,`metadata-${width}-${dark?"dark":"light"}.png`),fullPage:true});
    }
    for(const viewport of [{width:844,height:390,label:"phone-landscape"},{width:390,height:664,label:"toolbar-expanded"}]){
      await page.setViewportSize(viewport);await page.emulateMedia({colorScheme:"dark",reducedMotion:"reduce"});await page.goto(base+"/settings/timetables/");
      await page.locator("#timetableList article").first().getByRole("button",{name:"删除"}).click();
      const geometry=await page.evaluate(()=>{const box=document.querySelector("#deleteDialog").getBoundingClientRect(),viewport=document.documentElement.clientWidth;return{left:box.left,right:viewport-box.right,overflow:document.documentElement.scrollWidth-viewport}});
      check(Math.abs(geometry.left-geometry.right)<=1&&geometry.left>=15&&geometry.overflow<=0,`delete dialog ${viewport.label} reduced-motion geometry ${JSON.stringify(geometry)}`);
      check(await page.evaluate(()=>document.activeElement?.id==="deleteDialog"&&!document.querySelector("#deleteDialog [data-close-dialog]").matches(":focus-visible")),`delete dialog ${viewport.label} touch focus preserved`);
      await page.locator("#deleteDialog [data-close-dialog]").click();
    }
    const fresh = await browser.newContext({viewport:{width:390,height:844}});
    const onboardingPage = await fresh.newPage();
    await onboardingPage.goto(base + "/today/");
    await onboardingPage.waitForSelector("[data-onboarding-dialog][open]");
    check(await onboardingPage.locator("[data-onboarding-dialog]").isVisible(), "first-ever welcome shown");
    await onboardingPage.locator("[data-dismiss-onboarding]").click();
    await onboardingPage.goto(base + "/settings/timetables/");
    await onboardingPage.getByRole("button", {name:"新建课表"}).click();
    await onboardingPage.locator("#nameForm button[type=submit]").click();
    await onboardingPage.waitForSelector("#timetableList article");
    await onboardingPage.locator("#timetableList article").getByRole("button", {name:"删除"}).click();
    await onboardingPage.locator("#confirmDelete").click();
    await onboardingPage.waitForSelector("#noTimetables:not([hidden])");
    await onboardingPage.goto(base + "/today/");
    await onboardingPage.waitForSelector("#emptyState:not([hidden])");
    check(!(await onboardingPage.locator("[data-onboarding-dialog]").isVisible()), "later no-table does not replay welcome");
    await onboardingPage.goto(base + "/local-status/");
    await onboardingPage.waitForFunction(() => document.querySelector("#empty")?.textContent.includes("尚未保存课程表"));
    check(await onboardingPage.locator("#data").isHidden(), "Local Data no-active empty state");
    await fresh.close();
    const faultContext=await browser.newContext();
    await faultContext.addInitScript(() => {Object.defineProperty(indexedDB,"open",{configurable:true,value:()=>{throw Error("SYNTHETIC_STORAGE_FAILURE");}});});
    const faultPage=await faultContext.newPage();await faultPage.goto(base+"/local-status/");
    await faultPage.waitForFunction(() => document.querySelector("#empty")?.textContent.includes("无法读取本机课程数据"));
    check(await faultPage.locator("#data").isHidden(),"Local Data genuine storage error remains distinct");
    await faultContext.close();
    console.log(JSON.stringify({result:"MULTI_TIMETABLE_UI_PASS",assertions,viewports:"390/430/768/1280 x light/dark + phone landscape + toolbar-expanded reduced motion",screenshots:evidence}));
  } finally { await context.close(); await browser.close(); server.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; server.close(); });
