"use strict";
const assert=require("node:assert/strict"),http=require("node:http"),fs=require("node:fs"),path=require("node:path");
const {chromium}=require("playwright"),site=path.resolve(__dirname,"../app"),out=require("./local-artifacts").evidenceDirectory("phase4b-review");
const executablePath=[path.join(process.env.LOCALAPPDATA||"","Google","Chrome","Application","chrome.exe"),path.join(process.env["PROGRAMFILES(X86)"]||"","Microsoft","Edge","Application","msedge.exe")].find(fs.existsSync);
const server=http.createServer((req,res)=>{let name=decodeURIComponent(new URL(req.url,"http://local").pathname);if(name.endsWith("/"))name+="index.html";const file=path.resolve(site,"."+name);if(!file.startsWith(site+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.writeHead(200,{"content-type":file.endsWith(".js")?"application/javascript":file.endsWith(".css")?"text/css":"text/html"});res.end(fs.readFileSync(file));});
const field=(courseId,field="title")=>({type:"FIELD_CONFLICT",courseId,courseTitle:courseId,field,previousSourceValue:"Course A",currentUserValue:"我的课程名称很长，用于检查小屏幕换行",newSourceValue:"教务系统最新课程名称也很长，用于检查布局"});
const result=(conflicts=[],extra={})=>({status:"MERGED",unchangedCourses:1,sourceUpdatedCourses:1,newCourses:1,sourceMissingCourses:0,sourceMissingItems:[],preservedCourseOverrides:1,preservedOccurrenceOverrides:0,preservedCancellations:0,preservedGroupings:0,conflicts,orphanedOccurrenceOverrides:[],invalidatedGroupings:[],requiresReview:true,...extra});
const begin=async(page,merge,{failCommit=false}={})=>page.evaluate(async({merge,failCommit})=>{
  window.__reviewCalls=[];window.__reviewStatus="";let first=true;
  await AnyClassReimportReview.start({commit:async hooks=>{window.__reviewCalls.push(hooks);if(first){first=false;const error=Error("REIMPORT_MERGE_REVIEW_REQUIRED");error.mergeResult=merge;throw error;}if(failCommit)throw Error("INJECTED_COMMIT_FAILURE");return {mergeResult:{...merge,requiresReview:false}};},onSuccess:()=>{window.__reviewStatus="SUCCESS"},onCancel:()=>{window.__reviewStatus="CANCELLED"},onFailure:()=>{window.__reviewStatus="FAILED"}});
}, {merge,failCommit});
(async()=>{
  await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
  const browser=await chromium.launch({headless:true,executablePath});
  const base=`http://127.0.0.1:${server.address().port}`;
  const page=await browser.newPage({viewport:{width:390,height:844},colorScheme:"dark"});
  fs.mkdirSync(out,{recursive:true});
  const cases=[];const check=(name,condition)=>{assert(condition,name);cases.push(name)};
  try{
    await page.goto(`http://127.0.0.1:${server.address().port}/import/?method=file`);
    check("safe-source-only-no-review",await page.evaluate(async()=>{let called=false;await AnyClassReimportReview.start({commit:async()=>({mergeResult:{status:"MERGED",sourceUpdatedCourses:1,newCourses:0}}),onSuccess:()=>{called=true}});return called&&document.querySelector("#reimportReview").hidden}));
    await begin(page,result([field("Course A")]));
    await page.locator("#reimportReview").screenshot({path:path.join(out,"single-unresolved-390-dark.png")});
    check("single-field",await page.locator(".reimport-review-card").count()===1);
    check("unresolved-blocks",await page.locator("#reimportReviewCommit").isDisabled());
    check("student-language",(await page.locator("#reimportReview").innerText()).includes("你的修改"));
    await page.getByRole("button",{name:/Course A，课程名称，保留我的修改/}).focus();await page.keyboard.press("Enter");
    check("keyboard-choice",await page.getByRole("button",{name:/Course A，课程名称，保留我的修改/}).getAttribute("aria-pressed")==="true");
    check("visible-keyboard-focus",(await page.getByRole("button",{name:/Course A，课程名称，保留我的修改/}).evaluate(button=>getComputedStyle(button).outlineStyle))==="solid");
    await page.getByRole("button",{name:/Course A，课程名称，保留我的修改/}).click();
    check("keep-mine",await page.getByRole("button",{name:/Course A，课程名称，保留我的修改/}).getAttribute("aria-pressed")==="true");
    await page.locator("#reimportReview").screenshot({path:path.join(out,"resolved-keep-mine-390-dark.png")});
    check("resolved-enables",await page.locator("#reimportReviewCommit").isEnabled());
    await page.getByRole("button",{name:/Course A，课程名称，使用最新内容/}).click();
    check("adopt-source",await page.getByRole("button",{name:/Course A，课程名称，使用最新内容/}).getAttribute("aria-pressed")==="true");
    await page.locator("#reimportReview").screenshot({path:path.join(out,"resolved-adopt-source-390-dark.png")});
    check("change-decision",await page.getByRole("button",{name:/Course A，课程名称，保留我的修改/}).getAttribute("aria-pressed")==="false");
    await page.locator("#reimportReviewCommit").click();
    check("final-success",await page.evaluate(()=>window.__reviewStatus)==="SUCCESS");
    check("choice-forwarded",await page.evaluate(()=>Object.values(window.__reviewCalls.at(-1).mergeResolutions)[0])==="ADOPT_SOURCE");
    await begin(page,result([field("Course A"),field("Course A","location"),field("Course B","teacher")]));
    await page.locator("#reimportReview").screenshot({path:path.join(out,"multiple-conflicts-390-dark.png")});
    check("multiple-same-course",await page.locator(".reimport-review-card").count()===3);
    check("multiple-courses",(await page.locator("#reimportReview").innerText()).includes("Course B"));
    check("progress",(await page.locator("#reimportReviewProgress").innerText()).includes("3 项待确认"));
    await page.locator("#reimportReviewCancel").click();
    check("cancel",await page.evaluate(()=>window.__reviewStatus)==="CANCELLED");
    check("cancel-no-commit",await page.evaluate(()=>window.__reviewCalls.length)===1);
    await begin(page,result([],{sourceMissingCourses:1,sourceMissingItems:[{courseId:"A",courseTitle:"Course A",hasUserChanges:true}]}));
    await page.locator("#reimportReview").screenshot({path:path.join(out,"source-missing-390-dark.png")});
    check("source-missing",(await page.locator("#reimportReview").innerText()).includes("不在教务系统的最新课表中"));
    check("source-missing-blocks",await page.locator("#reimportReviewCommit").isDisabled());
    await page.locator(".reimport-review-ack input").check();
    await page.locator("#reimportReview").screenshot({path:path.join(out,"ready-to-commit-390-dark.png")});
    check("source-missing-confirm",await page.locator("#reimportReviewCommit").isEnabled());
    await page.locator("#reimportReviewCommit").click();
    await begin(page,result([],{orphanedOccurrenceOverrides:[{type:"ORPHANED_OCCURRENCE_OVERRIDE",courseId:"A",occurrenceId:"private-internal"}]}));
    check("occurrence-blocks",await page.locator("#reimportReviewCommit").isDisabled());
    check("occurrence-no-internal-id",!(await page.locator("#reimportReview").innerText()).includes("private-internal"));
    await page.locator("#reimportReviewCancel").click();
    await begin(page,result([],{invalidatedGroupings:[{type:"GROUPING_REVIEW",reason:"GROUPING_PERIODS_NOT_ADJACENT"}]}));
    await page.locator("#reimportReview").screenshot({path:path.join(out,"invalid-grouping-390-dark.png")});
    check("grouping-blocks",await page.locator("#reimportReviewCommit").isDisabled());
    check("grouping-no-id",!(await page.locator("#reimportReview").innerText()).includes("GROUPING_PERIODS_NOT_ADJACENT"));
    await page.locator("#reimportReviewCancel").click();
    await begin(page,result([field("Course A")]),{failCommit:true});
    await page.getByRole("button",{name:/Course A，课程名称，保留我的修改/}).click();await page.locator("#reimportReviewCommit").click();
    check("failure-retryable",(await page.locator("#reimportReviewFeedback").innerText()).includes("未完成")&&await page.locator("#reimportReviewCommit").isEnabled());
    await page.locator("#reimportReview").screenshot({path:path.join(out,"commit-failure-390-dark.png")});
    check("failure-choice-preserved",await page.getByRole("button",{name:/Course A，课程名称，保留我的修改/}).getAttribute("aria-pressed")==="true");
    await page.reload();check("refresh-restart",await page.locator("#reimportReview").isHidden());
    check("no-old-routes",!fs.existsSync(path.join(site,"import-mobile","index.html"))&&!fs.existsSync(path.join(site,"import-file","index.html")));
    const baseFile={schemaVersion:1,school:{id:"school-demo",name:"Example University"},semester:{academicYear:"2026-2027",term:"1"},meetings:[{courseName:"Course A",weekday:1,startPeriod:1,endPeriod:2,weeks:[1,2],teacher:"Teacher A",locationRaw:"Building A101"},{courseName:"Course B",weekday:2,startPeriod:3,endPeriod:4,weeks:[1,2],teacher:"Teacher B",locationRaw:"Building B202"}]};
    const selectFile=async(content,name)=>{await page.goto(`http://127.0.0.1:${server.address().port}/import/?method=file`);await page.locator("#fileInput").setInputFiles({name,mimeType:"application/json",buffer:Buffer.from(JSON.stringify(content))});await page.locator("#filePreview:not([hidden])").waitFor();await page.locator("#fileSemesterStart").fill("2026-08-31");};
    await selectFile(baseFile,"base.json");await page.locator("#fileSave").click();await page.waitForFunction(()=>/已保存/.test(document.querySelector("#fileSubmitMessage").textContent));
    const courseId=await page.evaluate(async()=>{const bundle=await AnyClassTimetableRepository.readActiveBundle(),course=bundle.model.courses.find(row=>row.title==="Course A"),db=await AnyClassStorageV2.openDb();const tx=db.transaction("courseOverrides","readwrite");tx.objectStore("courseOverrides").put({courseId:course.courseId,fields:{location:"My Building"},updatedAt:new Date().toISOString()});await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=tx.onerror=()=>reject(tx.error)});db.close();return course.courseId;});
    const changedFile={...baseFile,meetings:[{...baseFile.meetings[0],locationRaw:"New Building"},baseFile.meetings[1]]};
    await selectFile(changedFile,"changed.json");await page.locator("#fileSave").click();await page.locator("#reimportReview:not([hidden])").waitFor();
    check("json-field-review",(await page.locator("#reimportReview").innerText()).includes("导入文件最新内容"));
    check("json-unresolved-block",await page.locator("#reimportReviewCommit").isDisabled());
    await page.getByRole("button",{name:/Course A，地点，保留我的修改/}).click();await page.locator("#reimportReviewCommit").click();await page.waitForFunction(()=>/已更新/.test(document.querySelector("#fileSubmitMessage").textContent));
    await page.locator("#filePreview").screenshot({path:path.join(out,"json-commit-success-390-dark.png")});
    check("json-commit-preserves-choice",await page.evaluate(async id=>{const bundle=await AnyClassTimetableRepository.readActiveBundle();return bundle.model.courses.find(row=>row.courseId===id)?.location==="New Building"&&bundle.model.courseOverrides.find(row=>row.courseId===id)?.fields.location==="My Building";},courseId));
    await page.goto(base+"/import/");
    const withoutB={...baseFile,meetings:[changedFile.meetings[0]]};await selectFile(withoutB,"missing.json");await page.locator("#fileSave").click();await page.locator("#reimportReview:not([hidden])").waitFor();
    check("json-source-missing-review",(await page.locator("#reimportReview").innerText()).includes("不在导入文件的最新课表中"));
    await page.locator("#reimportReviewCancel").click();check("json-cancel-no-archive",await page.evaluate(async()=>{const bundle=await AnyClassTimetableRepository.readActiveBundle();return bundle.model.courses.some(row=>row.title==="Course B"&&!row.sourceMissing)}));
    await page.locator("#fileSave").click();await page.locator("#reimportReview:not([hidden])").waitFor();await page.locator(".reimport-review-ack input").check();assert(await page.locator("#reimportReviewCommit").isEnabled(),await page.locator("#reimportReview").innerText());await page.locator("#reimportReviewCommit").click();await page.waitForFunction(()=>/已更新/.test(document.querySelector("#fileSubmitMessage").textContent));
    check("json-source-missing-approved",await page.evaluate(async()=>{const db=await AnyClassStorageV2.openDb();try{const rows=await new Promise((resolve,reject)=>{const request=db.transaction("courses").objectStore("courses").getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return rows.some(row=>row.title==="Course B"&&row.sourceMissing&&row.suppressed)}finally{db.close()}}));
    await page.goto(base+"/import/");
    fs.mkdirSync(out,{recursive:true});
    const shots=[];for(const [width,height,theme] of [[390,844,"dark"],[390,844,"light"],[430,932,"dark"],[430,932,"light"],[1024,768,"light"],[1280,800,"light"],[1440,900,"dark"],[1440,900,"light"]]){
      await page.setViewportSize({width,height});await page.emulateMedia({colorScheme:theme});await begin(page,result([field("Course A"),field("Course B","location")],{sourceMissingCourses:1,sourceMissingItems:[{courseId:"C",courseTitle:"Course C",hasUserChanges:true}]}));
      const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);check(`no-overflow-${width}-${theme}`,!overflow);
      const name=`review-${width}-${theme}.png`;await page.locator("#reimportReview").screenshot({path:path.join(out,name)});shots.push(name);await page.locator("#reimportReviewCancel").click();
    }
    console.log(JSON.stringify({cases,caseCount:cases.length,screenshots:shots,directory:out}));
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1});
