"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),cp=require("node:child_process");
const gate=path.resolve(__dirname,"../tools/public-repository-privacy-gate.js"),token={pass:"ANYCLASS_PUBLIC_REPOSITORY_PRIVACY_GATE_PASS",blocked:"ANYCLASS_PUBLIC_REPOSITORY_PRIVACY_GATE_BLOCKED"};
const run=(repo,config)=>{const env={...process.env};if(config)env.ANYCLASS_PUBLIC_PRIVACY_DENYLIST=config;else delete env.ANYCLASS_PUBLIC_PRIVACY_DENYLIST;const result=cp.spawnSync(process.execPath,[gate,"--repo",repo],{env,encoding:"utf8"});return{code:result.status,out:result.stdout.trim()}};
const temp=fs.mkdtempSync(path.join(os.tmpdir(),"anyclass-privacy-gate-"));cp.execFileSync("git",["init","-q",temp]);cp.execFileSync("git",["-C",temp,"config","user.email","developer@example.com"]);cp.execFileSync("git",["-C",temp,"config","user.name","Example Developer"]);fs.writeFileSync(path.join(temp,"README.md"),"Synthetic public source\n");cp.execFileSync("git",["-C",temp,"add","README.md"]);cp.execFileSync("git",["-C",temp,"commit","-qm","synthetic baseline"]);
const valid=path.join(temp,"deny.json"),empty=path.join(temp,"empty.json"),bad=path.join(temp,"bad.json");fs.writeFileSync(valid,JSON.stringify({version:1,terms:["private-school-marker"]}));fs.writeFileSync(empty,JSON.stringify({version:1,terms:[]}));fs.writeFileSync(bad,"{");
assert.deepEqual(run(temp,null),{code:1,out:token.blocked});assert.deepEqual(run(temp,empty),{code:1,out:token.blocked});assert.deepEqual(run(temp,bad),{code:1,out:token.blocked});assert.deepEqual(run(temp,valid),{code:0,out:token.pass});
fs.writeFileSync(path.join(temp,"README.md"),"private-school-marker\n");assert.deepEqual(run(temp,valid),{code:1,out:token.blocked});fs.writeFileSync(path.join(temp,"README.md"),encodeURIComponent("private-school-marker"));assert.deepEqual(run(temp,valid),{code:1,out:token.blocked});
console.log(JSON.stringify({missing:"BLOCKED",empty:"BLOCKED",malformed:"BLOCKED",clean:"PASS",literal:"BLOCKED",encoded:"BLOCKED",result:"PASS"},null,2));
