"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,".."),site=path.join(root,"app"),read=relative=>fs.readFileSync(path.join(site,relative),"utf8");
const allFiles=(directory,out=[])=>{for(const entry of fs.readdirSync(directory,{withFileTypes:true})){const absolute=path.join(directory,entry.name);entry.isDirectory()?allFiles(absolute,out):out.push(absolute)}return out};
const publicText=allFiles(site).filter(file=>/\.(?:html|js|json|txt|md|css)$/i.test(file)).map(file=>fs.readFileSync(file,"utf8")).join("\n");
const config=read("assets/timetable/school-config.js"),contract=read("assets/timetable/school-profile.js"),adapter=read("assets/adapters/zhengfang-v9.js"),importPage=read("import/index.html"),shell=read("assets/timetable/product-shell.js");
assert(config.includes('id:"school-demo"')&&config.includes('displayName:"Example University"')&&config.includes('"https://jw.example.edu"'),"synthetic profile");
assert(contract.includes("AnyClassSchoolProfileRegistry")&&contract.includes("matchOrigin"),"SchoolProfile contract");
assert(!/AnyClassSchoolProfiles\.[A-Za-z0-9_-]+|TimetableSchoolConfigs\.[A-Za-z0-9_-]+/.test(adapter),"adapter imports concrete profile");
assert(adapter.includes("schoolProfileCandidates: []"),"generic adapter detection");
assert(!fs.existsSync(path.join(site,"import-mobile"))&&!fs.existsSync(path.join(site,"import-file")),"retired routes remain absent");
for(const value of ["高级设置 / 手动安装","手动配置","ios-shortcut-parser-shortcut.txt"])assert(!importPage.includes(value),`obsolete import copy ${value}`);
for(const value of ['data-import-panel="mobile"','data-import-panel="file"','new URL(location.href).searchParams.get("method")'])assert(importPage.includes(value),`unified import ${value}`);
assert(shell.includes('const DISPLAY_NAME_KEY = "anyclass.timetable.displayName"'),"canonical preference key");
assert(shell.includes('window.HeyAaronShell = shellApi'),"legacy API alias");
assert(shell.includes('"anyclass:timetable-updated"'),"canonical event");
assert(read("assets/timetable/import-file-core.js").includes("root.AnyClassTimetableFile = api"),"canonical file API");
assert(read("assets/timetable/import-file-storage.js").includes("root.AnyClassTimetableFileStorage=storage"),"canonical file storage API");
assert(fs.existsSync(path.join(root,"tools/public-repository-privacy-gate.js")),"privacy gate required");
assert(fs.existsSync(path.join(root,"docs/architecture/public-private-boundary.md")),"boundary documentation required");
assert(!/\/import-(?:mobile|file)\//.test(publicText),"retired route reference");
console.log(JSON.stringify({schoolProfiles:["school-demo"],concreteProfileImports:0,retiredRoutes:"ABSENT",legacyMigration:"PRESENT",privacyGate:"REQUIRED",result:"PUBLIC_CONTRACT_PASS"},null,2));
